export interface Demo {
  id: string
  name: string
  slug: string
  industry: string
  package: string
  description: string
  features: string[]
  colors: {
    primary: string
    secondary: string
    accent: string
  }
  layout: 'modern' | 'classic' | 'minimal' | 'bold' | 'elegant' | 'industrial'
  heroImage?: string
  mockupImage?: string
}

export const allDemos: Demo[] = [
  // ========== PLUG & PLAY DEMOS (Simple 4-page sites) ==========
  {
    id: 'barbershop-plug',
    name: 'Classic Cuts Barbershop',
    slug: 'classic-cuts-barbershop',
    industry: 'Beauty & Personal Care',
    package: 'Plug and Play - $250',
    description: 'Professional barbershop website demo featuring services menu, pricing packages, gallery, and easy contact form. Perfect template for local barber shops seeking online presence.',
    features: ['Home', 'Services', 'Pricing', 'Contact Form'],
    colors: { primary: '#1a1a1a', secondary: '#8b7355', accent: '#c9a96e' },
    layout: 'classic',
  },
  {
    id: 'handyman-plug',
    name: 'Fix-It Fast Handyman',
    slug: 'fixit-fast-handyman',
    industry: 'Home Services',
    package: 'Plug and Play - $250',
    description: 'Handyman business website demo with comprehensive service listings, pricing estimates, service area coverage, and quick contact options. Ideal for home repair professionals.',
    features: ['Home', 'Services', 'About', 'Contact'],
    colors: { primary: '#2c5f2d', secondary: '#97bc62', accent: '#ff6b35' },
    layout: 'bold',
  },
  {
    id: 'photography-plug',
    name: 'Lens & Light Photography',
    slug: 'lens-light-photography',
    industry: 'Creative Services',
    package: 'Plug and Play - $250',
    description: 'Stunning photography portfolio website demo featuring responsive image galleries, package pricing, session booking, and elegant minimal design for creative professionals.',
    features: ['Home', 'Portfolio', 'Packages', 'Contact'],
    colors: { primary: '#2d3142', secondary: '#4f5d75', accent: '#bfc0c0' },
    layout: 'minimal',
  },
  {
    id: 'cleaning-plug',
    name: 'Sparkle Clean Services',
    slug: 'sparkle-clean-services',
    industry: 'Home Services',
    package: 'Plug and Play - $250',
    description: 'Professional cleaning service website demo with residential and commercial service packages, online booking, pricing calculator, and customer testimonials section.',
    features: ['Home', 'Services', 'Pricing', 'Contact'],
    colors: { primary: '#0077b6', secondary: '#00b4d8', accent: '#90e0ef' },
    layout: 'modern',
  },
  {
    id: 'tutor-plug',
    name: 'Smart Start Tutoring',
    slug: 'smart-start-tutoring',
    industry: 'Education',
    package: 'Plug and Play - $250',
    description: 'Tutoring service website demo featuring subject expertise listings, tutor profiles, session scheduling system, student progress tracking, and parent communication portal.',
    features: ['Home', 'Subjects', 'About', 'Contact'],
    colors: { primary: '#5f0f40', secondary: '#9a031e', accent: '#fb8b24' },
    layout: 'elegant',
  },

  // ========== WEBSITE REBUILD DEMOS (Updated existing sites) ==========
  {
    id: 'landscaping-rebuild',
    name: 'Green Valley Landscaping',
    slug: 'green-valley-landscaping',
    industry: 'Home Services',
    package: 'Website Rebuild - $350',
    description: 'Modernized landscaping website with project gallery and seasonal services.',
    features: ['Home', 'Services', 'Gallery', 'Testimonials', 'Contact'],
    colors: { primary: '#386641', secondary: '#6a994e', accent: '#a7c957' },
    layout: 'modern',
  },
  {
    id: 'dentist-rebuild',
    name: 'Bright Smile Dental',
    slug: 'bright-smile-dental',
    industry: 'Healthcare',
    package: 'Website Rebuild - $350',
    description: 'Professional dental practice site with services, team, and online booking.',
    features: ['Home', 'Services', 'Our Team', 'Patient Info', 'Book Appointment', 'Contact'],
    colors: { primary: '#023e8a', secondary: '#0077b6', accent: '#48cae4' },
    layout: 'elegant',
  },
  {
    id: 'accounting-rebuild',
    name: 'Peak Financial Advisors',
    slug: 'peak-financial-advisors',
    industry: 'Professional Services',
    package: 'Website Rebuild - $350',
    description: 'Trustworthy financial services website with service details and resources.',
    features: ['Home', 'Services', 'About', 'Resources', 'Client Portal Login', 'Contact'],
    colors: { primary: '#14213d', secondary: '#fca311', accent: '#e5e5e5' },
    layout: 'classic',
  },
  {
    id: 'salon-rebuild',
    name: 'Glamour Studio Salon',
    slug: 'glamour-studio-salon',
    industry: 'Beauty & Personal Care',
    package: 'Website Rebuild - $350',
    description: 'Stylish salon website with services, stylists, and online booking.',
    features: ['Home', 'Services', 'Stylists', 'Gallery', 'Book Now', 'Contact'],
    colors: { primary: '#d00000', secondary: '#dc2f02', accent: '#e85d04' },
    layout: 'bold',
  },

  // ========== STANDARD WEBSITE DEMOS (Professional 8-12 page sites) ==========
  {
    id: 'hvac-standard',
    name: 'Cool Breeze HVAC',
    slug: 'cool-breeze-hvac',
    industry: 'Home Services',
    package: 'Standard Website - $850',
    description: 'Complete HVAC company website with service areas, emergency contact, and financing.',
    features: ['Home', 'Services', 'Service Areas', 'Financing', 'Emergency Service', 'About', 'Testimonials', 'Blog', 'Contact'],
    colors: { primary: '#003049', secondary: '#d62828', accent: '#f77f00' },
    layout: 'industrial',
  },
  {
    id: 'law-firm-standard',
    name: 'Justice & Associates Law',
    slug: 'justice-associates-law',
    industry: 'Legal',
    package: 'Standard Website - $850',
    description: 'Professional law firm website with practice areas, attorney profiles, and case results.',
    features: ['Home', 'Practice Areas', 'Our Attorneys', 'Case Results', 'Client Resources', 'About', 'FAQ', 'Blog', 'Contact'],
    colors: { primary: '#1a1a2e', secondary: '#16213e', accent: '#c9a227' },
    layout: 'elegant',
  },
  {
    id: 'plumbing-standard',
    name: 'Premier Plumbing Pros',
    slug: 'premier-plumbing-pros',
    industry: 'Home Services',
    package: 'Standard Website - $850',
    description: 'Full-service plumbing website with emergency dispatch, coupons, and service guarantees.',
    features: ['Home', 'Residential', 'Commercial', 'Emergency Service', 'Coupons', 'About', 'Reviews', 'Service Areas', 'Contact'],
    colors: { primary: '#0466c8', secondary: '#0353a4', accent: '#023e7d' },
    layout: 'modern',
  },
  {
    id: 'realestate-standard',
    name: 'Skyline Realty Group',
    slug: 'skyline-realty-group',
    industry: 'Real Estate',
    package: 'Standard Website - $850',
    description: 'Real estate agency website with property search, agent profiles, and market insights.',
    features: ['Home', 'Featured Listings', 'Our Agents', 'Buyer Resources', 'Seller Resources', 'Market Trends', 'About', 'Testimonials', 'Contact'],
    colors: { primary: '#000814', secondary: '#001d3d', accent: '#ffc300' },
    layout: 'modern',
  },
  {
    id: 'gym-standard',
    name: 'Iron Temple Fitness',
    slug: 'iron-temple-fitness',
    industry: 'Health & Fitness',
    package: 'Standard Website - $850',
    description: 'Fitness center website with class schedules, trainers, membership options.',
    features: ['Home', 'Classes', 'Trainers', 'Memberships', 'Schedule', 'Amenities', 'Success Stories', 'Blog', 'Join Now'],
    colors: { primary: '#c1121f', secondary: '#780000', accent: '#fdf0d5' },
    layout: 'bold',
  },
  {
    id: 'veterinary-standard',
    name: 'Paws & Care Animal Hospital',
    slug: 'paws-care-animal-hospital',
    industry: 'Healthcare',
    package: 'Standard Website - $850',
    description: 'Veterinary clinic website with services, pet care tips, and appointment booking.',
    features: ['Home', 'Services', 'Our Vets', 'Pet Care Tips', 'New Patients', 'Emergency Care', 'FAQ', 'Testimonials', 'Contact'],
    colors: { primary: '#38a3a5', secondary: '#57cc99', accent: '#80ed99' },
    layout: 'modern',
  },

  // ========== E-COMMERCE DEMOS ==========
  {
    id: 'boutique-ecommerce',
    name: 'Bella Boutique Fashion',
    slug: 'bella-boutique-fashion',
    industry: 'Retail',
    package: 'E-Commerce Website - $1,100',
    description: 'Online clothing boutique with product catalog, shopping cart, and checkout.',
    features: ['Home', 'Shop', 'Collections', 'New Arrivals', 'Sale', 'Cart', 'Checkout', 'Account', 'About', 'Contact'],
    colors: { primary: '#9d4edd', secondary: '#c77dff', accent: '#e0aaff' },
    layout: 'elegant',
  },
  {
    id: 'bakery-ecommerce',
    name: 'Sweet Dreams Bakery',
    slug: 'sweet-dreams-bakery',
    industry: 'Food & Beverage',
    package: 'E-Commerce Website - $1,100',
    description: 'Online bakery with custom cake orders, delivery scheduling, and gift options.',
    features: ['Home', 'Menu', 'Custom Cakes', 'Order Online', 'Catering', 'Delivery', 'Cart', 'Account', 'About', 'Contact'],
    colors: { primary: '#d62828', secondary: '#f77f00', accent: '#fcbf49' },
    layout: 'modern',
  },
  {
    id: 'supplements-ecommerce',
    name: 'Peak Performance Supplements',
    slug: 'peak-performance-supplements',
    industry: 'Health & Fitness',
    package: 'E-Commerce Website - $1,100',
    description: 'Supplement store with product filtering, subscriptions, and nutrition guides.',
    features: ['Home', 'Shop', 'Categories', 'Subscriptions', 'Bundles', 'Nutrition Guides', 'Cart', 'Account', 'Reviews', 'Contact'],
    colors: { primary: '#001219', secondary: '#005f73', accent: '#0a9396' },
    layout: 'bold',
  },
  {
    id: 'jewelry-ecommerce',
    name: 'Timeless Treasures Jewelry',
    slug: 'timeless-treasures-jewelry',
    industry: 'Retail',
    package: 'E-Commerce Website - $1,100',
    description: 'Jewelry store with high-res product images, wish lists, and gift registry.',
    features: ['Home', 'Shop', 'Collections', 'Custom Design', 'Gift Registry', 'Wishlist', 'Cart', 'Checkout', 'About', 'Contact'],
    colors: { primary: '#0d1b2a', secondary: '#1b263b', accent: '#c9a227' },
    layout: 'elegant',
  },
  {
    id: 'craftbeer-ecommerce',
    name: 'Hoppy Trails Craft Beer',
    slug: 'hoppy-trails-craft-beer',
    industry: 'Food & Beverage',
    package: 'E-Commerce Website - $1,100',
    description: 'Craft beer shop with age verification, beer finder, and local pickup.',
    features: ['Home', 'Shop Beers', 'Breweries', 'Beer Finder', 'Local Pickup', 'Subscriptions', 'Cart', 'Account', 'Events', 'Contact'],
    colors: { primary: '#582f0e', secondary: '#7f4f24', accent: '#936639' },
    layout: 'industrial',
  },
  {
    id: 'plants-ecommerce',
    name: 'Urban Jungle Plant Shop',
    slug: 'urban-jungle-plant-shop',
    industry: 'Retail',
    package: 'E-Commerce Website - $1,100',
    description: 'Plant nursery with care guides, plant care subscriptions, and delivery.',
    features: ['Home', 'Shop Plants', 'Care Guides', 'Plant Quiz', 'Subscriptions', 'Delivery', 'Cart', 'Account', 'Blog', 'Contact'],
    colors: { primary: '#2d6a4f', secondary: '#40916c', accent: '#52b788' },
    layout: 'modern',
  },
  {
    id: 'coffee-ecommerce',
    name: 'Roasted Perfection Coffee',
    slug: 'roasted-perfection-coffee',
    industry: 'Food & Beverage',
    package: 'E-Commerce Website - $1,100',
    description: 'Coffee roaster with subscriptions, brewing guides, and wholesale options.',
    features: ['Home', 'Shop Coffee', 'Subscriptions', 'Wholesale', 'Brewing Guides', 'Our Story', 'Cart', 'Account', 'Blog', 'Contact'],
    colors: { primary: '#3e2723', secondary: '#5d4037', accent: '#8d6e63' },
    layout: 'modern',
  },
  {
    id: 'petfood-ecommerce',
    name: 'Happy Paws Pet Supplies',
    slug: 'happy-paws-pet-supplies',
    industry: 'Retail',
    package: 'E-Commerce Website - $1,100',
    description: 'Pet supply store with auto-delivery, product recommendations, and vet-approved products.',
    features: ['Home', 'Shop by Pet', 'Subscriptions', 'Sale', 'Auto-Delivery', 'Vet Approved', 'Cart', 'Account', 'Resources', 'Contact'],
    colors: { primary: '#f4a261', secondary: '#e76f51', accent: '#264653' },
    layout: 'modern',
  },

  // ========== PREMIUM BUILD DEMOS (Advanced features) ==========
  {
    id: 'restaurant-premium',
    name: 'Gourmet Kitchen Restaurant',
    slug: 'gourmet-kitchen-restaurant',
    industry: 'Food & Beverage',
    package: 'Premium Build - $2,000',
    description: 'Restaurant with online ordering, table reservations, loyalty program, and admin dashboard.',
    features: ['Home', 'Menu', 'Order Online', 'Reservations', 'Private Events', 'Catering', 'Loyalty Program', 'Gift Cards', 'Admin Dashboard', 'Contact'],
    colors: { primary: '#9b2226', secondary: '#ae2012', accent: '#ee9b00' },
    layout: 'elegant',
  },
  {
    id: 'contractor-premium',
    name: 'BuildRight Construction',
    slug: 'buildright-construction',
    industry: 'Construction',
    package: 'Premium Build - $2,000',
    description: 'Construction company with project portfolio, quote builder, client portal, and project tracking.',
    features: ['Home', 'Services', 'Portfolio', 'Quote Builder', 'Client Portal', 'Project Tracking', 'Testimonials', 'Resources', 'About', 'Contact'],
    colors: { primary: '#ff6700', secondary: '#ff8500', accent: '#ffa300' },
    layout: 'industrial',
  },
  {
    id: 'medical-premium',
    name: 'HealthFirst Medical Group',
    slug: 'healthfirst-medical-group',
    industry: 'Healthcare',
    package: 'Premium Build - $2,000',
    description: 'Medical practice with patient portal, appointment scheduling, telehealth, and prescription refills.',
    features: ['Home', 'Services', 'Our Doctors', 'Patient Portal', 'Book Appointment', 'Telehealth', 'Prescriptions', 'Insurance', 'Resources', 'Contact'],
    colors: { primary: '#0353a4', secondary: '#006ba6', accent: '#0496ff' },
    layout: 'modern',
  },
  {
    id: 'autorepair-premium',
    name: 'Precision Auto Repair',
    slug: 'precision-auto-repair',
    industry: 'Automotive',
    package: 'Premium Build - $2,000',
    description: 'Auto shop with service scheduling, vehicle history, cost estimator, and customer accounts.',
    features: ['Home', 'Services', 'Schedule Service', 'Cost Estimator', 'Customer Portal', 'Vehicle History', 'Coupons', 'Reviews', 'About', 'Contact'],
    colors: { primary: '#03071e', secondary: '#370617', accent: '#dc2f02' },
    layout: 'industrial',
  },
  {
    id: 'spa-premium',
    name: 'Serenity Spa & Wellness',
    slug: 'serenity-spa-wellness',
    industry: 'Beauty & Personal Care',
    package: 'Premium Build - $2,000',
    description: 'Luxury spa with membership portal, package builder, gift certificates, and booking system.',
    features: ['Home', 'Services', 'Packages', 'Book Now', 'Memberships', 'Gift Certificates', 'Member Portal', 'Shop Products', 'About', 'Contact'],
    colors: { primary: '#6a4c93', secondary: '#8b6d9c', accent: '#c9ada7' },
    layout: 'elegant',
  },
  {
    id: 'logistics-premium',
    name: 'Swift Logistics Services',
    slug: 'swift-logistics-services',
    industry: 'Transportation',
    package: 'Premium Build - $2,000',
    description: 'Logistics company with shipment tracking, quote calculator, customer portal, and reporting.',
    features: ['Home', 'Services', 'Get Quote', 'Track Shipment', 'Customer Portal', 'Reporting', 'Service Areas', 'About', 'Careers', 'Contact'],
    colors: { primary: '#005f73', secondary: '#0a9396', accent: '#94d2bd' },
    layout: 'modern',
  },

  // ========== CUSTOM BUSINESS PLATFORM DEMOS ==========
  {
    id: 'property-management',
    name: 'Elite Property Management',
    slug: 'elite-property-management',
    industry: 'Real Estate',
    package: 'Custom Business Platform - $5,000',
    description: 'Complete property management system with tenant portal, maintenance tracking, payment processing, and owner dashboards.',
    features: ['Home', 'Properties', 'Tenant Portal', 'Owner Portal', 'Maintenance Requests', 'Payment Processing', 'Lease Management', 'Reports', 'Messaging', 'Contact'],
    colors: { primary: '#003566', secondary: '#001d3d', accent: '#ffc300' },
    layout: 'modern',
  },
  {
    id: 'staffing-agency',
    name: 'Premier Staffing Solutions',
    slug: 'premier-staffing-solutions',
    industry: 'Professional Services',
    package: 'Custom Business Platform - $5,000',
    description: 'Staffing agency with job board, candidate portal, client portal, timesheet management, and invoicing.',
    features: ['Home', 'Job Board', 'Candidate Portal', 'Client Portal', 'Timesheets', 'Invoicing', 'Reporting', 'Compliance', 'Resources', 'Contact'],
    colors: { primary: '#1b263b', secondary: '#415a77', accent: '#778da9' },
    layout: 'modern',
  },
  {
    id: 'event-planning',
    name: 'Celebration Events Co.',
    slug: 'celebration-events-company',
    industry: 'Events',
    package: 'Custom Business Platform - $5,000',
    description: 'Event planning with client portal, vendor management, budget tracking, timeline builder, and guest management.',
    features: ['Home', 'Services', 'Portfolio', 'Client Portal', 'Vendor Directory', 'Budget Tracker', 'Timeline Builder', 'Guest Management', 'Resources', 'Contact'],
    colors: { primary: '#d62828', secondary: '#f77f00', accent: '#fcbf49' },
    layout: 'elegant',
  },

  // ========== ENTERPRISE PLATFORM DEMOS ==========
  {
    id: 'franchise-enterprise',
    name: 'FastServe Franchise Network',
    slug: 'fastserve-franchise-network',
    industry: 'Multi-Location',
    package: 'Enterprise Platform - $7,500',
    description: 'Multi-location franchise with central admin, location dashboards, inventory sync, and corporate reporting.',
    features: ['Home', 'Locations', 'Franchise Portal', 'Central Admin', 'Inventory Management', 'Multi-Store Reporting', 'Training Portal', 'Marketing Tools', 'Corporate Resources', 'Contact'],
    colors: { primary: '#bc4749', secondary: '#f2cc8f', accent: '#81b29a' },
    layout: 'modern',
  },
  {
    id: 'manufacturing-enterprise',
    name: 'TechPro Manufacturing',
    slug: 'techpro-manufacturing',
    industry: 'Manufacturing',
    package: 'Enterprise Platform - $7,500',
    description: 'Manufacturing platform with inventory management, production scheduling, quality control, and B2B ordering.',
    features: ['Home', 'Products', 'B2B Portal', 'Production Dashboard', 'Inventory Management', 'Quality Control', 'Order Management', 'Supplier Portal', 'Analytics', 'Contact'],
    colors: { primary: '#0b090a', secondary: '#161a1d', accent: '#ba181b' },
    layout: 'industrial',
  },

  // ========== SPECIALTY ADD-ON SHOWCASE DEMOS ==========
  {
    id: 'booking-showcase',
    name: 'Perfect Appointments Demo',
    slug: 'booking-system-showcase',
    industry: 'Showcase',
    package: 'Feature: Booking Calendar ($90)',
    description: 'Demonstration of advanced booking system with calendar sync, reminders, and staff scheduling.',
    features: ['Multi-Staff Booking', 'Calendar Sync', 'Email Reminders', 'SMS Notifications', 'Recurring Appointments', 'Cancellation Management'],
    colors: { primary: '#3a86ff', secondary: '#8338ec', accent: '#ff006e' },
    layout: 'modern',
  },
  {
    id: 'analytics-showcase',
    name: 'Business Intelligence Dashboard',
    slug: 'analytics-dashboard-showcase',
    industry: 'Showcase',
    package: 'Feature: Analytics Dashboard ($150)',
    description: 'Real-time analytics dashboard with custom metrics, data visualization, and report generation.',
    features: ['Real-Time Metrics', 'Custom Reports', 'Data Visualization', 'Export Options', 'Performance Tracking', 'Goal Setting'],
    colors: { primary: '#1b4965', secondary: '#62b6cb', accent: '#bee9e8' },
    layout: 'modern',
  },
  {
    id: 'membership-showcase',
    name: 'Member Hub Portal',
    slug: 'membership-portal-showcase',
    industry: 'Showcase',
    package: 'Feature: Membership Portal ($200)',
    description: 'Complete membership system with tiers, benefits, content access, and member directory.',
    features: ['Membership Tiers', 'Exclusive Content', 'Member Directory', 'Benefits Tracking', 'Renewal Management', 'Member Dashboard'],
    colors: { primary: '#7209b7', secondary: '#560bad', accent: '#b5179e' },
    layout: 'modern',
  },
  {
    id: 'crm-showcase',
    name: 'Customer Relationship Manager',
    slug: 'crm-system-showcase',
    industry: 'Showcase',
    package: 'Feature: Advanced CRM ($210)',
    description: 'Full CRM system with lead tracking, pipeline management, email automation, and task management.',
    features: ['Lead Management', 'Pipeline Tracking', 'Email Automation', 'Task Management', 'Contact History', 'Sales Reporting'],
    colors: { primary: '#2b2d42', secondary: '#8d99ae', accent: '#ef233c' },
    layout: 'modern',
  },
  {
    id: 'inventory-showcase',
    name: 'Stock Management System',
    slug: 'inventory-management-showcase',
    industry: 'Showcase',
    package: 'Feature: Inventory Management ($200)',
    description: 'Advanced inventory system with stock tracking, low-stock alerts, supplier management, and reporting.',
    features: ['Stock Tracking', 'Low Stock Alerts', 'Supplier Management', 'Purchase Orders', 'Stock Reports', 'Barcode Scanning'],
    colors: { primary: '#06aed5', secondary: '#086788', accent: '#f0c808' },
    layout: 'modern',
  },
  {
    id: 'workflow-showcase',
    name: 'Automation Builder',
    slug: 'workflow-automation-showcase',
    industry: 'Showcase',
    package: 'Feature: Workflow Automation ($150)',
    description: 'Workflow automation system with triggers, actions, conditional logic, and integration options.',
    features: ['Visual Workflow Builder', 'Custom Triggers', 'Automated Actions', 'Conditional Logic', 'Integration Hub', 'Workflow Templates'],
    colors: { primary: '#6a4c93', secondary: '#1982c4', accent: '#8ac926' },
    layout: 'modern',
  },
]

export const demoCategories = [
  { name: 'All Demos', slug: 'all', count: allDemos.length },
  { name: 'Plug & Play', slug: 'plug-play', count: allDemos.filter(d => d.package.includes('Plug and Play')).length },
  { name: 'Website Rebuild', slug: 'rebuild', count: allDemos.filter(d => d.package.includes('Rebuild')).length },
  { name: 'Standard Sites', slug: 'standard', count: allDemos.filter(d => d.package.includes('Standard')).length },
  { name: 'E-Commerce', slug: 'ecommerce', count: allDemos.filter(d => d.package.includes('E-Commerce')).length },
  { name: 'Premium Builds', slug: 'premium', count: allDemos.filter(d => d.package.includes('Premium Build')).length },
  { name: 'Business Platforms', slug: 'business-platform', count: allDemos.filter(d => d.package.includes('Custom Business Platform')).length },
  { name: 'Enterprise', slug: 'enterprise', count: allDemos.filter(d => d.package.includes('Enterprise')).length },
  { name: 'Feature Showcases', slug: 'showcase', count: allDemos.filter(d => d.industry === 'Showcase').length },
]

export const demosByIndustry = {
  'Home Services': allDemos.filter(d => d.industry === 'Home Services'),
  'Healthcare': allDemos.filter(d => d.industry === 'Healthcare'),
  'Food & Beverage': allDemos.filter(d => d.industry === 'Food & Beverage'),
  'Retail': allDemos.filter(d => d.industry === 'Retail'),
  'Professional Services': allDemos.filter(d => d.industry === 'Professional Services'),
  'Beauty & Personal Care': allDemos.filter(d => d.industry === 'Beauty & Personal Care'),
  'Health & Fitness': allDemos.filter(d => d.industry === 'Health & Fitness'),
  'Legal': allDemos.filter(d => d.industry === 'Legal'),
  'Real Estate': allDemos.filter(d => d.industry === 'Real Estate'),
  'Automotive': allDemos.filter(d => d.industry === 'Automotive'),
  'Construction': allDemos.filter(d => d.industry === 'Construction'),
  'Transportation': allDemos.filter(d => d.industry === 'Transportation'),
  'Events': allDemos.filter(d => d.industry === 'Events'),
  'Manufacturing': allDemos.filter(d => d.industry === 'Manufacturing'),
  'Multi-Location': allDemos.filter(d => d.industry === 'Multi-Location'),
  'Creative Services': allDemos.filter(d => d.industry === 'Creative Services'),
  'Education': allDemos.filter(d => d.industry === 'Education'),
}
