export type MSPServiceCategory = 'managed-it' | 'cybersecurity' | 'cloud' | 'support'

export interface MSPService {
  id: string
  name: string
  slug: string
  category: MSPServiceCategory
  price: number
  priceLabel: string
  billingType: 'monthly' | 'one-time' | 'custom'
  shortDescription: string
  longDescription: string
  features: string[]
  benefits: string[]
  useCases: string[]
  deliverables: string[]
  timeline: string
  seoKeywords: string[]
  metaTitle: string
  metaDescription: string
}

export const managedITServices: MSPService[] = [
  {
    id: 'essential-it',
    name: 'Essential IT',
    slug: 'essential-it',
    category: 'managed-it',
    price: 99,
    priceLabel: '$99/user/mo',
    billingType: 'monthly',
    shortDescription: 'Complete IT support with security included - more value than competitors at $125+',
    longDescription: `Get more than basic IT support at a competitive price. Our Essential IT package includes everything small businesses need: helpdesk, monitoring, security essentials, AND email security with phishing protection - features competitors charge extra for. Perfect for businesses with 1-15 employees who want reliable IT without paying enterprise prices. You get $125+ worth of services at $99/user.`,
    features: [
      'Remote helpdesk support (M-F 8AM-6PM)',
      '24/7 system monitoring & alerts',
      'Enterprise antivirus/anti-malware',
      'Email security & phishing protection (included)',
      'Password manager for all users (included)',
      'Windows/Mac updates and patches',
      'Basic network monitoring',
      'Monthly health reports',
      '4-hour response time SLA',
      'Unlimited support tickets',
      'Remote desktop support',
      'New user setup assistance',
    ],
    benefits: [
      'Predictable monthly IT costs',
      'Email security included (competitors charge $5-10 extra)',
      'Password manager included (competitors charge $3-5 extra)',
      'Professional support without hiring IT staff',
      'Reduced downtime from proactive monitoring',
      'Focus on your business, not IT problems',
    ],
    useCases: [
      'Small businesses with 1-15 employees',
      'Startups needing IT support on a budget',
      'Remote teams needing centralized IT',
      'Professional services firms (lawyers, accountants)',
      'Small retail or service businesses',
    ],
    deliverables: [
      'Helpdesk portal access',
      'Monitoring agent installation',
      'Antivirus & email security deployment',
      'Password manager setup',
      'Monthly reports',
      'Documented IT procedures',
    ],
    timeline: 'Setup in 1-2 days',
    seoKeywords: ['managed IT support Houston', 'small business IT support Conroe', 'helpdesk services Texas', 'IT support near me'],
    metaTitle: 'Essential IT | $99/user/mo',
    metaDescription: 'Complete IT support with email security & password manager included. $99/user/month - more value than competitors at $125+. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'business-pro',
    name: 'Business Pro',
    slug: 'business-pro',
    category: 'managed-it',
    price: 129,
    priceLabel: '$129/user/mo',
    billingType: 'monthly',
    shortDescription: 'Full managed IT with backup, security monitoring, and MFA - $175+ value at $129',
    longDescription: `Our most popular plan delivers $175+ worth of IT services at $129/user. Business Pro includes everything in Essential IT plus cloud backup, dark web monitoring, MFA setup, priority 2-hour support, and vendor management. While competitors charge $150-175 for basic managed IT, we include security features they charge extra for. Ideal for businesses with 5-30 employees who need comprehensive IT without enterprise pricing.`,
    features: [
      'All Essential IT features',
      'Priority support (2-hour response SLA)',
      'Cloud backup with daily snapshots (included)',
      'Dark web credential monitoring (included)',
      'Multi-factor authentication setup (included)',
      'Network administration',
      'Vendor management (ISP, software, hardware)',
      'Quarterly business reviews',
      'IT asset inventory tracking',
      'Software license management',
      'New employee onboarding/offboarding',
      'Hardware procurement assistance',
      'After-hours emergency support',
      'Web content filtering',
    ],
    benefits: [
      'Cloud backup included (competitors charge $10/user extra)',
      'Dark web monitoring included (competitors charge $5-10 extra)',
      'MFA setup included (competitors charge $5 extra)',
      'Single point of contact for all IT needs',
      'Faster issue resolution with priority support',
      'Strategic IT planning included',
    ],
    useCases: [
      'Growing businesses with 5-30 employees',
      'Companies with remote/hybrid workers',
      'Businesses handling customer data',
      'Multi-location small businesses',
      'Professional services requiring uptime',
    ],
    deliverables: [
      'All Essential IT deliverables',
      'Cloud backup solution configured',
      'MFA deployed to all users',
      'Dark web monitoring alerts',
      'Network documentation',
      'Vendor contact management',
      'IT asset inventory',
      'Quarterly strategy meetings',
    ],
    timeline: 'Setup in 3-5 days',
    seoKeywords: ['managed IT services Houston', 'IT management Conroe', 'outsourced IT Texas', 'business IT support The Woodlands'],
    metaTitle: 'Business Pro IT | $129/user/mo',
    metaDescription: 'Full managed IT with backup, dark web monitoring & MFA included. $129/user - $175+ value. Priority support, vendor management. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'complete-it',
    name: 'Complete IT',
    slug: 'complete-it',
    category: 'managed-it',
    price: 179,
    priceLabel: '$179/user/mo',
    billingType: 'monthly',
    shortDescription: 'IT + Security combined - EDR, SIEM, training, and dedicated support in one package',
    longDescription: `The all-in-one IT and security solution for businesses that need enterprise-grade protection without enterprise complexity. Complete IT bundles our Business Pro managed IT with advanced cybersecurity - EDR, SIEM monitoring, security awareness training, and quarterly assessments. Competitors charge $200-250+ for this level of service. Ideal for businesses with 10-50 employees, especially those handling sensitive data or facing compliance requirements.`,
    features: [
      'All Business Pro features',
      'Endpoint Detection & Response (EDR)',
      'SIEM log monitoring and analysis',
      'Security awareness training program',
      'Quarterly vulnerability assessments',
      'Dedicated account manager',
      'Extended support hours (7AM-9PM)',
      '1-hour response SLA',
      'Incident response support',
      'Compliance documentation assistance',
      'Advanced threat hunting',
      'Privileged access management',
      'USB device control',
      'Monthly executive security reports',
    ],
    benefits: [
      'IT + Security in one package (saves $50+/user vs separate)',
      'EDR included (competitors charge $20-30 extra)',
      'Security training included (competitors charge $3-5 extra)',
      'Dedicated account manager who knows your business',
      'Meet compliance requirements (HIPAA, PCI basics)',
      'Reduced breach risk with advanced monitoring',
    ],
    useCases: [
      'Businesses with 10-50 employees',
      'Companies handling sensitive customer data',
      'Healthcare-adjacent businesses',
      'Financial services firms',
      'Businesses with compliance needs',
      'Companies concerned about ransomware',
    ],
    deliverables: [
      'All Business Pro deliverables',
      'EDR deployment and configuration',
      'SIEM setup and monitoring',
      'Security training platform access',
      'Quarterly assessment reports',
      'Incident response playbook',
      'Compliance checklist documentation',
    ],
    timeline: 'Setup in 5-7 days',
    seoKeywords: ['managed IT and security Houston', 'MSP with cybersecurity Texas', 'complete IT services Conroe', 'IT security bundle'],
    metaTitle: 'Complete IT | $179/user/mo',
    metaDescription: 'IT + cybersecurity in one package. EDR, SIEM, security training, dedicated support. $179/user - saves $50+ vs separate services. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'enterprise-it-solutions',
    name: 'Enterprise IT Solutions',
    slug: 'enterprise-it-solutions',
    category: 'managed-it',
    price: 0,
    priceLabel: 'Custom Quote',
    billingType: 'custom',
    shortDescription: 'Full-service IT department replacement with dedicated resources and 24/7 support',
    longDescription: `Enterprise-grade IT solutions for established businesses. Our Enterprise package provides a complete IT department replacement with dedicated account management, 24/7 support, advanced security, compliance assistance, and strategic IT consulting. We handle everything from daily support to long-term IT strategy, infrastructure projects, and digital transformation initiatives. Ideal for businesses with 50+ employees or those with complex IT requirements.`,
    features: [
      'All Complete IT features',
      'Dedicated account team (not just manager)',
      '24/7/365 support with 30-minute SLA',
      'Full compliance management (HIPAA, PCI, SOC2, CMMC)',
      'Disaster recovery planning and testing',
      'Virtual CIO services',
      'Infrastructure project management',
      'Cloud migration services included',
      'Advanced network design',
      'Annual penetration testing',
      'Tabletop exercises',
      'Board-level security reporting',
    ],
    benefits: [
      'Full IT department capabilities',
      'Dedicated resources who know your business',
      '24/7 support for critical operations',
      'Full compliance expertise and documentation',
      'Strategic technology planning',
      'Reduced risk with advanced security',
    ],
    useCases: [
      'Businesses with 50+ employees',
      'Healthcare organizations (HIPAA)',
      'Financial services (compliance needs)',
      'Multi-location enterprises',
      'Companies undergoing digital transformation',
    ],
    deliverables: [
      'All Complete IT deliverables',
      'Dedicated account team',
      'Full compliance documentation',
      'Disaster recovery plan and testing',
      'Annual penetration test report',
      'Strategic IT roadmap',
      'Monthly executive reports',
      'Board presentation materials',
    ],
    timeline: 'Onboarding in 2-4 weeks',
    seoKeywords: ['enterprise IT services Houston', 'managed service provider Texas', 'MSP Houston', 'IT outsourcing Conroe'],
    metaTitle: 'Enterprise IT | Custom Quote',
    metaDescription: 'Enterprise managed IT services with 24/7 support, dedicated resources, compliance, and strategic consulting. Custom solutions for 50+ employee businesses.',
  },
]

export const cybersecurityServices: MSPService[] = [
  {
    id: 'security-essentials',
    name: 'Security Essentials',
    slug: 'security-essentials',
    category: 'cybersecurity',
    price: 29,
    priceLabel: '$29/user/mo',
    billingType: 'monthly',
    shortDescription: 'Core cybersecurity protection - antivirus, firewall management, email security',
    longDescription: `Essential cybersecurity protection for small businesses. Our Security Essentials package provides the core security tools every business needs: enterprise-grade antivirus, email security to block phishing and malware, and firewall management. We monitor your systems 24/7 for threats and provide monthly security reports so you always know your protection status. Perfect for businesses that need solid security without complexity.`,
    features: [
      'Enterprise antivirus/anti-malware',
      'Email security and spam filtering',
      'Phishing protection',
      'Firewall management',
      '24/7 threat monitoring',
      'Security patch management',
      'Web content filtering',
      'USB device control',
      'Monthly security reports',
      'Basic security awareness tips',
    ],
    benefits: [
      'Block ransomware and malware',
      'Prevent phishing attacks',
      'Protect sensitive business data',
      'Meet basic compliance requirements',
      'Peace of mind with 24/7 monitoring',
      'Simple, set-and-forget security',
    ],
    useCases: [
      'Small businesses needing basic protection',
      'Companies handling customer data',
      'Businesses with remote employees',
      'Professional services firms',
      'Retail and e-commerce businesses',
    ],
    deliverables: [
      'Security software deployment',
      'Firewall configuration',
      'Email security setup',
      'Monthly security reports',
      'Security best practices guide',
    ],
    timeline: 'Deployed in 1-2 days',
    seoKeywords: ['cybersecurity services Houston', 'small business security Conroe', 'email security Texas', 'antivirus management'],
    metaTitle: 'Security Essentials | $29/user/mo',
    metaDescription: 'Essential cybersecurity for small businesses. Antivirus, email security, phishing protection. $29/user/month. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'advanced-threat-protection',
    name: 'Advanced Threat Protection',
    slug: 'advanced-threat-protection',
    category: 'cybersecurity',
    price: 59,
    priceLabel: '$59/user/mo',
    billingType: 'monthly',
    shortDescription: 'Advanced security with EDR, SIEM, dark web monitoring, and incident response',
    longDescription: `Advanced cybersecurity for businesses facing sophisticated threats. Our Advanced Threat Protection package goes beyond basic security with Endpoint Detection and Response (EDR), Security Information and Event Management (SIEM), dark web monitoring for compromised credentials, and incident response support. We actively hunt for threats in your environment and respond immediately when threats are detected. Essential for businesses handling sensitive data or facing regulatory requirements.`,
    features: [
      'All Security Essentials features',
      'Endpoint Detection & Response (EDR)',
      'SIEM log monitoring and analysis',
      'Dark web credential monitoring',
      'Security incident response',
      'Advanced threat hunting',
      'Multi-factor authentication (MFA)',
      'Privileged access management',
      'Vulnerability scanning',
      'Quarterly security assessments',
      'Security awareness training',
      'Incident response plan',
    ],
    benefits: [
      'Detect advanced threats in real-time',
      'Rapid response to security incidents',
      'Know if credentials are compromised',
      'Meet compliance requirements',
      'Reduce breach risk significantly',
      'Expert security team on your side',
    ],
    useCases: [
      'Businesses handling sensitive data',
      'Healthcare organizations',
      'Financial services companies',
      'Legal and accounting firms',
      'Companies with compliance requirements',
    ],
    deliverables: [
      'All Security Essentials deliverables',
      'EDR deployment and configuration',
      'SIEM setup and monitoring',
      'Dark web monitoring alerts',
      'Incident response playbook',
      'Quarterly security reports',
      'Security awareness training program',
    ],
    timeline: 'Deployed in 3-5 days',
    seoKeywords: ['advanced threat protection Houston', 'EDR security Texas', 'cybersecurity monitoring Conroe', 'managed security services'],
    metaTitle: 'Advanced Threat Protection | $59/user',
    metaDescription: 'Advanced cybersecurity with EDR, SIEM, dark web monitoring. Threat hunting and incident response. $59/user/month. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'security-assessment',
    name: 'Security Assessment',
    slug: 'security-assessment',
    category: 'cybersecurity',
    price: 1500,
    priceLabel: '$1,500',
    billingType: 'one-time',
    shortDescription: 'Comprehensive security audit with vulnerability assessment and remediation plan',
    longDescription: `Understand your security posture with a comprehensive security assessment. Our Security Assessment service provides a thorough evaluation of your IT infrastructure, policies, and practices. We identify vulnerabilities, assess risks, and deliver a prioritized remediation plan. Perfect for businesses wanting to understand their security gaps, preparing for compliance audits, or evaluating their current security measures. Includes executive summary for leadership and technical details for IT teams.`,
    features: [
      'Network vulnerability scanning',
      'External penetration testing',
      'Password and access review',
      'Email security assessment',
      'Endpoint security evaluation',
      'Policy and procedure review',
      'Compliance gap analysis',
      'Risk scoring and prioritization',
      'Executive summary report',
      'Technical findings report',
      'Remediation roadmap',
      '60-minute review meeting',
    ],
    benefits: [
      'Understand your security weaknesses',
      'Prioritized action plan',
      'Support compliance requirements',
      'Reduce breach risk',
      'Justify security investments',
      'Expert third-party perspective',
    ],
    useCases: [
      'Businesses unsure of security status',
      'Companies preparing for audits',
      'Organizations after security incidents',
      'Businesses acquiring/merging',
      'Annual security checkups',
    ],
    deliverables: [
      'Executive summary (1-2 pages)',
      'Technical findings report (detailed)',
      'Vulnerability scan results',
      'Risk assessment matrix',
      'Prioritized remediation plan',
      'Compliance checklist (if applicable)',
    ],
    timeline: '1-2 weeks',
    seoKeywords: ['security assessment Houston', 'vulnerability assessment Texas', 'penetration testing Conroe', 'security audit'],
    metaTitle: 'Security Assessment | $1,500',
    metaDescription: 'Comprehensive security assessment with vulnerability scanning, penetration testing, and remediation plan. $1,500 one-time. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'compliance-services',
    name: 'Compliance Services',
    slug: 'compliance-services',
    category: 'cybersecurity',
    price: 0,
    priceLabel: 'Custom Quote',
    billingType: 'custom',
    shortDescription: 'HIPAA, PCI-DSS, SOC2, CMMC compliance assistance and documentation',
    longDescription: `Navigate complex compliance requirements with expert guidance. Our Compliance Services help businesses achieve and maintain compliance with HIPAA, PCI-DSS, SOC2, CMMC, and other regulatory frameworks. We provide gap assessments, policy development, technical controls implementation, and ongoing compliance monitoring. Our team has experience with healthcare, financial services, government contractors, and other regulated industries. We help you pass audits and maintain compliance year-round.`,
    features: [
      'Compliance gap assessment',
      'Policy and procedure development',
      'Technical controls implementation',
      'Employee training programs',
      'Risk assessment documentation',
      'Vendor management assistance',
      'Audit preparation support',
      'Ongoing compliance monitoring',
      'Annual compliance reviews',
      'Incident response planning',
      'Business continuity planning',
      'Documentation management',
    ],
    benefits: [
      'Achieve compliance faster',
      'Reduce audit stress and costs',
      'Avoid fines and penalties',
      'Win contracts requiring compliance',
      'Protect customer trust',
      'Expert guidance throughout',
    ],
    useCases: [
      'Healthcare organizations (HIPAA)',
      'Payment processors (PCI-DSS)',
      'Government contractors (CMMC)',
      'SaaS companies (SOC2)',
      'Financial services (various)',
    ],
    deliverables: [
      'Gap assessment report',
      'Policy documentation package',
      'Technical controls checklist',
      'Training materials',
      'Audit-ready documentation',
      'Compliance roadmap',
    ],
    timeline: 'Varies by framework',
    seoKeywords: ['HIPAA compliance Houston', 'PCI compliance Texas', 'SOC2 preparation', 'CMMC compliance Conroe'],
    metaTitle: 'Compliance Services | HIPAA, PCI, SOC2',
    metaDescription: 'Expert compliance services for HIPAA, PCI-DSS, SOC2, CMMC. Gap assessments, policy development, audit preparation. Houston, Conroe, The Woodlands.',
  },
]

export const cloudServices: MSPService[] = [
  {
    id: 'microsoft-365-management',
    name: 'Microsoft 365 Management',
    slug: 'microsoft-365-management',
    category: 'cloud',
    price: 15,
    priceLabel: '$15/user/mo',
    billingType: 'monthly',
    shortDescription: 'Complete Microsoft 365 administration, support, and optimization',
    longDescription: `Maximize your Microsoft 365 investment with professional management. We handle everything from initial setup to ongoing administration, user management, security configuration, and support. Our M365 Management service ensures your tenant is secure, optimized, and your team is productive. Includes Teams administration, SharePoint management, Exchange Online configuration, and license optimization to reduce costs.`,
    features: [
      'Microsoft 365 tenant administration',
      'User provisioning and management',
      'Security and compliance configuration',
      'Teams and SharePoint administration',
      'Exchange Online management',
      'License optimization',
      'OneDrive for Business setup',
      'Conditional access policies',
      'Email signature management',
      'Shared mailbox management',
      'Distribution group management',
      'M365 support and troubleshooting',
    ],
    benefits: [
      'Optimized Microsoft 365 environment',
      'Reduced licensing costs',
      'Improved security posture',
      'Better team collaboration',
      'Expert support for M365 issues',
      'Stay current with new features',
    ],
    useCases: [
      'Businesses using Microsoft 365',
      'Companies migrating to M365',
      'Teams needing collaboration tools',
      'Organizations requiring email security',
      'Businesses needing SharePoint',
    ],
    deliverables: [
      'Tenant configuration audit',
      'Security baseline implementation',
      'User management procedures',
      'License optimization report',
      'M365 documentation',
    ],
    timeline: 'Setup in 1-3 days',
    seoKeywords: ['Microsoft 365 management Houston', 'M365 administration Texas', 'Office 365 support Conroe', 'Microsoft 365 consulting'],
    metaTitle: 'Microsoft 365 Management | $15/user',
    metaDescription: 'Professional Microsoft 365 management and administration. Security, optimization, support. $15/user/month. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'cloud-backup',
    name: 'Cloud Backup Solutions',
    slug: 'cloud-backup',
    category: 'cloud',
    price: 10,
    priceLabel: '$10/user/mo',
    billingType: 'monthly',
    shortDescription: 'Automated cloud backup for endpoints, servers, and Microsoft 365',
    longDescription: `Protect your business data with automated, secure cloud backup. Our Cloud Backup Solutions provide comprehensive data protection for endpoints, servers, and Microsoft 365. Daily automated backups, encrypted storage, and rapid recovery ensure your business can survive any data loss scenario. From accidental deletion to ransomware, we keep your data safe and recoverable. Includes backup monitoring, testing, and restore assistance.`,
    features: [
      'Endpoint backup (workstations/laptops)',
      'Server backup',
      'Microsoft 365 backup',
      'Automated daily backups',
      'Encrypted cloud storage',
      'Point-in-time recovery',
      'Backup monitoring and alerts',
      'Monthly backup testing',
      'Rapid restore assistance',
      'Retention policies (30/60/90 days)',
      'Bandwidth throttling',
      'Bare-metal recovery option',
    ],
    benefits: [
      'Never lose critical business data',
      'Recover from ransomware attacks',
      'Meet compliance backup requirements',
      'Quick restoration when needed',
      'Peace of mind with monitoring',
      'Affordable data protection',
    ],
    useCases: [
      'Businesses with critical data',
      'Companies concerned about ransomware',
      'Compliance requirements (data retention)',
      'Businesses with mobile workers',
      'Organizations using Microsoft 365',
    ],
    deliverables: [
      'Backup software deployment',
      'Backup policy configuration',
      'Initial full backup',
      'Monitoring dashboard access',
      'Recovery documentation',
    ],
    timeline: 'Deployed in 1-2 days',
    seoKeywords: ['cloud backup Houston', 'data backup services Texas', 'Microsoft 365 backup Conroe', 'business backup solutions'],
    metaTitle: 'Cloud Backup | $10/user/mo',
    metaDescription: 'Automated cloud backup for endpoints and Microsoft 365. Ransomware protection, fast recovery. $10/user/month. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'cloud-migration',
    name: 'Cloud Migration',
    slug: 'cloud-migration',
    category: 'cloud',
    price: 2500,
    priceLabel: 'From $2,500',
    billingType: 'one-time',
    shortDescription: 'Migrate on-premise infrastructure to cloud (Azure, AWS, Google Cloud)',
    longDescription: `Move your business to the cloud with expert migration services. We plan and execute migrations from on-premise infrastructure to Azure, AWS, or Google Cloud. Our methodical approach minimizes downtime and ensures data integrity throughout the migration. Includes assessment, planning, migration execution, testing, and post-migration optimization. Perfect for businesses modernizing infrastructure or eliminating aging servers.`,
    features: [
      'Infrastructure assessment',
      'Cloud architecture design',
      'Migration planning and timeline',
      'Data migration',
      'Application migration',
      'Email migration (if needed)',
      'Identity migration (Active Directory)',
      'Testing and validation',
      'Cutover coordination',
      'Post-migration optimization',
      'Documentation and training',
      '30 days post-migration support',
    ],
    benefits: [
      'Eliminate aging server hardware',
      'Reduce infrastructure costs',
      'Improve reliability and uptime',
      'Enable remote work capabilities',
      'Scale resources as needed',
      'Disaster recovery built-in',
    ],
    useCases: [
      'Businesses with aging servers',
      'Companies enabling remote work',
      'Organizations needing scalability',
      'Businesses reducing IT overhead',
      'Companies consolidating locations',
    ],
    deliverables: [
      'Migration assessment report',
      'Cloud architecture documentation',
      'Migration runbook',
      'Completed migration',
      'Post-migration report',
      'Training documentation',
    ],
    timeline: '2-8 weeks depending on scope',
    seoKeywords: ['cloud migration Houston', 'Azure migration Texas', 'AWS migration Conroe', 'cloud consulting'],
    metaTitle: 'Cloud Migration | From $2,500',
    metaDescription: 'Expert cloud migration to Azure, AWS, or Google Cloud. Assessment, planning, execution. From $2,500. Houston, Conroe, The Woodlands.',
  },
]

export const supportServices: MSPService[] = [
  {
    id: 'break-fix-support',
    name: 'Break/Fix Support',
    slug: 'break-fix-support',
    category: 'support',
    price: 125,
    priceLabel: '$125/hour',
    billingType: 'one-time',
    shortDescription: 'On-demand IT support billed hourly for businesses not ready for managed services',
    longDescription: `Professional IT support when you need it, without monthly commitments. Our Break/Fix Support provides on-demand IT assistance billed hourly. Perfect for businesses with minimal IT needs, those testing our services before committing to managed IT, or for one-time projects. We handle troubleshooting, repairs, installations, and IT projects of all sizes. No contracts, no minimums, just expert help when you need it.`,
    features: [
      'Remote support',
      'On-site support (Houston/Conroe area)',
      'Hardware troubleshooting',
      'Software installation and support',
      'Network troubleshooting',
      'Virus and malware removal',
      'Data recovery assistance',
      'New computer setup',
      'Printer and peripheral support',
      'One-time projects',
    ],
    benefits: [
      'No monthly commitment',
      'Pay only for what you need',
      'Professional expertise on-demand',
      'Flexible scheduling',
      'Good for minimal IT needs',
      'Try before committing to managed',
    ],
    useCases: [
      'Small businesses with rare IT issues',
      'One-time IT projects',
      'Emergency IT support',
      'Businesses evaluating MSP services',
      'Supplement to internal IT',
    ],
    deliverables: [
      'Issue resolution',
      'Service documentation',
      'Recommendations for prevention',
    ],
    timeline: 'Same-day to next-day response',
    seoKeywords: ['IT support Houston', 'computer repair Conroe', 'on-demand IT Texas', 'hourly IT support'],
    metaTitle: 'Break/Fix IT Support | $125/hr',
    metaDescription: 'On-demand IT support billed hourly. No contracts, no minimums. $125/hour. Remote and on-site in Houston, Conroe, The Woodlands.',
  },
  {
    id: 'network-installation',
    name: 'Network Installation',
    slug: 'network-installation',
    category: 'support',
    price: 500,
    priceLabel: 'From $500',
    billingType: 'one-time',
    shortDescription: 'Business network design, installation, and configuration',
    longDescription: `Professional network installation for your business. We design and install business-grade networks including routers, switches, access points, and cabling. From small office setups to multi-floor installations, we ensure reliable, secure, and fast network connectivity. Includes network design, equipment recommendations, installation, configuration, and documentation. We also offer network upgrades and expansions for existing infrastructure.`,
    features: [
      'Network design and planning',
      'Equipment recommendations',
      'Router and firewall setup',
      'Switch installation',
      'Wireless access point deployment',
      'Network cabling (Cat6/Cat6a)',
      'VLAN configuration',
      'Guest network setup',
      'Network security configuration',
      'Speed and performance testing',
      'Network documentation',
      'Staff training',
    ],
    benefits: [
      'Reliable network connectivity',
      'Proper security configuration',
      'Scalable for growth',
      'Professional documentation',
      'Equipment warranty support',
      'Expert design and installation',
    ],
    useCases: [
      'New office setup',
      'Office relocation',
      'Network upgrades',
      'Adding wireless coverage',
      'Multi-floor installations',
    ],
    deliverables: [
      'Network design document',
      'Installed and configured equipment',
      'Network diagram',
      'Configuration documentation',
      'Speed test results',
    ],
    timeline: '1-5 days depending on scope',
    seoKeywords: ['network installation Houston', 'business networking Texas', 'office network setup Conroe', 'WiFi installation'],
    metaTitle: 'Network Installation | From $500',
    metaDescription: 'Professional business network installation. Design, equipment, cabling, configuration. From $500. Houston, Conroe, The Woodlands.',
  },
  {
    id: 'it-consulting',
    name: 'IT Consulting',
    slug: 'it-consulting',
    category: 'support',
    price: 150,
    priceLabel: '$150/hour',
    billingType: 'one-time',
    shortDescription: 'Strategic IT consulting for technology planning and decision-making',
    longDescription: `Make informed technology decisions with expert IT consulting. Our IT Consulting services help businesses plan technology investments, evaluate solutions, and develop IT strategies aligned with business goals. Whether you're planning a major technology initiative, evaluating vendors, or developing an IT roadmap, we provide unbiased expert guidance. Perfect for businesses making significant technology decisions or needing strategic IT direction.`,
    features: [
      'Technology strategy development',
      'IT roadmap planning',
      'Vendor evaluation and selection',
      'Budget planning assistance',
      'Security strategy',
      'Cloud strategy',
      'Digital transformation guidance',
      'IT process improvement',
      'Technology due diligence (M&A)',
      'RFP development',
      'Project oversight',
      'Executive briefings',
    ],
    benefits: [
      'Unbiased expert advice',
      'Avoid costly technology mistakes',
      'Align IT with business goals',
      'Informed vendor decisions',
      'Clear technology roadmap',
      'Strategic IT direction',
    ],
    useCases: [
      'Planning major IT investments',
      'Evaluating technology vendors',
      'Developing IT strategy',
      'Digital transformation planning',
      'M&A technology assessment',
    ],
    deliverables: [
      'Consulting report/recommendations',
      'Technology roadmap (if applicable)',
      'Vendor comparison (if applicable)',
      'Executive presentation',
    ],
    timeline: 'Varies by engagement',
    seoKeywords: ['IT consulting Houston', 'technology consulting Texas', 'IT strategy Conroe', 'virtual CIO'],
    metaTitle: 'IT Consulting | $150/hr',
    metaDescription: 'Expert IT consulting for technology strategy, vendor selection, and IT planning. $150/hour. Houston, Conroe, The Woodlands.',
  },
]

// Helper function to get all MSP services
export const allMSPServices: MSPService[] = [
  ...managedITServices,
  ...cybersecurityServices,
  ...cloudServices,
  ...supportServices,
]

// Get service by slug
export function getMSPServiceBySlug(slug: string): MSPService | undefined {
  return allMSPServices.find(service => service.slug === slug)
}
