export type MSPServiceCategory = 'managed-it' | 'cybersecurity' | 'cloud' | 'support'

export interface MSPService {
  id: string
  name: string
  slug: string
  category: MSPServiceCategory
  price: number
  priceLabel: string
  billingType: 'monthly' | 'one-time' | 'custom'
  shortDescription: string
  longDescription: string
  features: string[]
  benefits: string[]
  useCases: string[]
  deliverables: string[]
  timeline: string
  seoKeywords: string[]
  metaTitle: string
  metaDescription: string
  faqs?: { question: string; answer: string }[]
}

export const managedITServices: MSPService[] = [
  {
    id: 'essential-it',
    name: 'Essential IT',
    slug: 'essential-it',
    category: 'managed-it',
    price: 99,
    priceLabel: '$99/user/mo',
    billingType: 'monthly',
    shortDescription: 'Complete IT support with security included: more value than competitors at $125+',
    longDescription: `Get more than basic IT support at a competitive price. Our Essential IT package includes everything small businesses need: helpdesk, monitoring, security essentials, AND email security with phishing protection. These are features competitors charge extra for. Perfect for businesses with 1-15 employees who want reliable IT without paying enterprise prices. You get $125+ worth of services at $99/user.`,
    features: [
      'Remote helpdesk support (M-F 8AM-6PM)',
      '24/7 system monitoring & alerts',
      'Enterprise antivirus/anti-malware',
      'Email security & phishing protection (included)',
      'Password manager for all users (included)',
      'Windows/Mac updates and patches',
      'Basic network monitoring',
      'Monthly health reports',
      '4-hour response time SLA',
      'Unlimited support tickets',
      'Remote desktop support',
      'New user setup assistance',
    ],
    benefits: [
      'Predictable monthly IT costs',
      'Email security included (competitors charge $5-10 extra)',
      'Password manager included (competitors charge $3-5 extra)',
      'Professional support without hiring IT staff',
      'Reduced downtime from proactive monitoring',
      'Focus on your business, not IT problems',
    ],
    useCases: [
      'Small businesses with 1-15 employees',
      'Startups needing IT support on a budget',
      'Remote teams needing centralized IT',
      'Professional services firms (lawyers, accountants)',
      'Small retail or service businesses',
    ],
    deliverables: [
      'Helpdesk portal access',
      'Monitoring agent installation',
      'Antivirus & email security deployment',
      'Password manager setup',
      'Monthly reports',
      'Documented IT procedures',
    ],
    timeline: 'Setup in 1-2 days',
    seoKeywords: ['managed IT support Houston', 'small business IT support Conroe', 'helpdesk services Texas', 'IT support near me'],
    metaTitle: 'Houston IT Support with Security Included | $99/User/Mo',
    metaDescription: 'Complete IT support with email security & password manager included. $99/user/month with 4-hour response. Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'What is included in the $99/user/month Essential IT plan?',
        answer: 'Essential IT includes remote helpdesk support (M-F 8AM-6PM), 24/7 system monitoring and alerts, enterprise antivirus/anti-malware, email security and phishing protection, a password manager for all users, Windows/Mac updates and patches, monthly health reports, and a 4-hour response time SLA with unlimited support tickets.',
      },
      {
        question: 'Are email security and a password manager really included, or are they add-ons?',
        answer: 'Both are included in the base $99/user price. Many competitors charge $5-10 extra for email security and $3-5 extra for a password manager, so Essential IT bundles roughly $125+ worth of services into a $99 plan.',
      },
      {
        question: 'How fast is support response time?',
        answer: 'Essential IT includes a 4-hour response time SLA and unlimited support tickets, with remote desktop support and new user setup assistance included.',
      },
      {
        question: 'How long does it take to get set up?',
        answer: 'Essential IT is typically set up within 1-2 days, including monitoring agent installation, antivirus and email security deployment, and password manager setup.',
      },
    ],
  },
  {
    id: 'business-pro',
    name: 'Business Pro',
    slug: 'business-pro',
    category: 'managed-it',
    price: 129,
    priceLabel: '$129/user/mo',
    billingType: 'monthly',
    shortDescription: 'Full managed IT with backup, security monitoring, and MFA: $175+ value at $129',
    longDescription: `Our most popular plan delivers $175+ worth of IT services at $129/user. Business Pro includes everything in Essential IT plus cloud backup, dark web monitoring, MFA setup, priority 2-hour support, and vendor management. While competitors charge $150-175 for basic managed IT, we include security features they charge extra for. Ideal for businesses with 5-30 employees who need comprehensive IT without enterprise pricing.`,
    features: [
      'All Essential IT features',
      'Priority support (2-hour response SLA)',
      'Cloud backup with daily snapshots (included)',
      'Dark web credential monitoring (included)',
      'Multi-factor authentication setup (included)',
      'Network administration',
      'Vendor management (ISP, software, hardware)',
      'Quarterly business reviews',
      'IT asset inventory tracking',
      'Software license management',
      'New employee onboarding/offboarding',
      'Hardware procurement assistance',
      'After-hours emergency support',
      'Web content filtering',
    ],
    benefits: [
      'Cloud backup included (competitors charge $10/user extra)',
      'Dark web monitoring included (competitors charge $5-10 extra)',
      'MFA setup included (competitors charge $5 extra)',
      'Single point of contact for all IT needs',
      'Faster issue resolution with priority support',
      'Strategic IT planning included',
    ],
    useCases: [
      'Growing businesses with 5-30 employees',
      'Companies with remote/hybrid workers',
      'Businesses handling customer data',
      'Multi-location small businesses',
      'Professional services requiring uptime',
    ],
    deliverables: [
      'All Essential IT deliverables',
      'Cloud backup solution configured',
      'MFA deployed to all users',
      'Dark web monitoring alerts',
      'Network documentation',
      'Vendor contact management',
      'IT asset inventory',
      'Quarterly strategy meetings',
    ],
    timeline: 'Setup in 3-5 days',
    seoKeywords: ['managed IT services Houston', 'IT management Conroe', 'outsourced IT Texas', 'business IT support The Woodlands'],
    metaTitle: 'Houston Managed IT Pro | Backup & MFA | $129/User/Mo',
    metaDescription: 'Full managed IT with cloud backup, dark web monitoring & MFA. $129/user/month with 2-hour priority support. Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'What does Business Pro add on top of Essential IT?',
        answer: 'Business Pro includes everything in Essential IT plus priority 2-hour response support, cloud backup with daily snapshots, dark web credential monitoring, multi-factor authentication setup, network administration, vendor management, quarterly business reviews, IT asset inventory tracking, and software license management.',
      },
      {
        question: 'Is cloud backup really included in the price?',
        answer: 'Yes. Cloud backup with daily snapshots, dark web monitoring, and MFA setup are all included in the $129/user price. Competitors typically charge $10/user extra for backup, $5-10 extra for dark web monitoring, and $5 extra for MFA setup.',
      },
      {
        question: 'What is the support response time on Business Pro?',
        answer: 'Business Pro includes a 2-hour priority response SLA, along with after-hours emergency support.',
      },
      {
        question: 'How long does setup take?',
        answer: 'Business Pro is typically set up in 3-5 days, including MFA deployment to all users, cloud backup configuration, and network documentation.',
      },
      {
        question: 'Who is Business Pro designed for?',
        answer: 'It is built for growing businesses with 5-30 employees, companies with remote or hybrid workers, businesses handling customer data, and multi-location small businesses.',
      },
    ],
  },
  {
    id: 'complete-it',
    name: 'Complete IT',
    slug: 'complete-it',
    category: 'managed-it',
    price: 179,
    priceLabel: '$179/user/mo',
    billingType: 'monthly',
    shortDescription: 'IT + Security combined: EDR, SIEM, training, and dedicated support in one package',
    longDescription: `The all-in-one IT and security solution for businesses that need enterprise-grade protection without enterprise complexity. Complete IT bundles our Business Pro managed IT with advanced cybersecurity: EDR, SIEM monitoring, security awareness training, and quarterly assessments. Competitors charge $200-250+ for this level of service. Ideal for businesses with 10-50 employees, especially those handling sensitive data or facing compliance requirements.`,
    features: [
      'All Business Pro features',
      'Endpoint Detection & Response (EDR)',
      'SIEM log monitoring and analysis',
      'Security awareness training program',
      'Quarterly vulnerability assessments',
      'Dedicated account manager',
      'Extended support hours (7AM-9PM)',
      '1-hour response SLA',
      'Incident response support',
      'Compliance documentation assistance',
      'Advanced threat hunting',
      'Privileged access management',
      'USB device control',
      'Monthly executive security reports',
    ],
    benefits: [
      'IT + Security in one package (saves $50+/user vs separate)',
      'EDR included (competitors charge $20-30 extra)',
      'Security training included (competitors charge $3-5 extra)',
      'Dedicated account manager who knows your business',
      'Meet compliance requirements (HIPAA, PCI basics)',
      'Reduced breach risk with advanced monitoring',
    ],
    useCases: [
      'Businesses with 10-50 employees',
      'Companies handling sensitive customer data',
      'Healthcare-adjacent businesses',
      'Financial services firms',
      'Businesses with compliance needs',
      'Companies concerned about ransomware',
    ],
    deliverables: [
      'All Business Pro deliverables',
      'EDR deployment and configuration',
      'SIEM setup and monitoring',
      'Security training platform access',
      'Quarterly assessment reports',
      'Incident response playbook',
      'Compliance checklist documentation',
    ],
    timeline: 'Setup in 5-7 days',
    seoKeywords: ['managed IT and security Houston', 'MSP with cybersecurity Texas', 'complete IT services Conroe', 'IT security bundle'],
    metaTitle: 'Houston IT & Security Bundle | EDR, SIEM | $179/User/Mo',
    metaDescription: 'IT and cybersecurity combined. EDR, SIEM, security training, and dedicated support. $179/user/month. Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'What extra security does Complete IT add over Business Pro?',
        answer: 'Complete IT includes all Business Pro features plus Endpoint Detection & Response (EDR), SIEM log monitoring and analysis, a security awareness training program, quarterly vulnerability assessments, a dedicated account manager, advanced threat hunting, privileged access management, and USB device control.',
      },
      {
        question: 'What is the support response time and hours?',
        answer: 'Complete IT includes extended support hours from 7AM-9PM and a 1-hour response SLA, along with incident response support.',
      },
      {
        question: 'Does Complete IT help with compliance requirements?',
        answer: 'Yes, it includes compliance documentation assistance and can help meet basic HIPAA and PCI requirements. Businesses with more extensive compliance needs (full HIPAA, PCI-DSS, SOC2, or CMMC programs) should look at Compliance Services.',
      },
      {
        question: 'How long does setup take?',
        answer: 'Complete IT is typically set up in 5-7 days, including EDR deployment, SIEM setup and monitoring, and security training platform access.',
      },
      {
        question: 'Who is Complete IT built for?',
        answer: 'It is designed for businesses with 10-50 employees, especially those handling sensitive customer data, healthcare-adjacent businesses, financial services firms, and companies concerned about ransomware or compliance.',
      },
    ],
  },
  {
    id: 'enterprise-it-solutions',
    name: 'Enterprise IT Solutions',
    slug: 'enterprise-it-solutions',
    category: 'managed-it',
    price: 0,
    priceLabel: 'Custom Quote',
    billingType: 'custom',
    shortDescription: 'Full-service IT department replacement with dedicated resources and 24/7 support',
    longDescription: `Enterprise-grade IT solutions for established businesses. Our Enterprise package provides a complete IT department replacement with dedicated account management, 24/7 support, advanced security, compliance assistance, and strategic IT consulting. We handle everything from daily support to long-term IT strategy, infrastructure projects, and digital transformation initiatives. Ideal for businesses with 50+ employees or those with complex IT requirements.`,
    features: [
      'All Complete IT features',
      'Dedicated account team (not just manager)',
      '24/7/365 support with 30-minute SLA',
      'Full compliance management (HIPAA, PCI, SOC2, CMMC)',
      'Disaster recovery planning and testing',
      'Virtual CIO services',
      'Infrastructure project management',
      'Cloud migration services included',
      'Advanced network design',
      'Annual penetration testing',
      'Tabletop exercises',
      'Board-level security reporting',
    ],
    benefits: [
      'Full IT department capabilities',
      'Dedicated resources who know your business',
      '24/7 support for critical operations',
      'Full compliance expertise and documentation',
      'Strategic technology planning',
      'Reduced risk with advanced security',
    ],
    useCases: [
      'Businesses with 50+ employees',
      'Healthcare organizations (HIPAA)',
      'Financial services (compliance needs)',
      'Multi-location enterprises',
      'Companies undergoing digital transformation',
    ],
    deliverables: [
      'All Complete IT deliverables',
      'Dedicated account team',
      'Full compliance documentation',
      'Disaster recovery plan and testing',
      'Annual penetration test report',
      'Strategic IT roadmap',
      'Monthly executive reports',
      'Board presentation materials',
    ],
    timeline: 'Onboarding in 2-4 weeks',
    seoKeywords: ['enterprise IT services Houston', 'managed service provider Texas', 'MSP Houston', 'IT outsourcing Conroe'],
    metaTitle: 'Houston Enterprise IT Outsourcing | Custom Quote',
    metaDescription: 'Enterprise managed IT services with 24/7 support, dedicated resources, compliance, and strategic consulting. Custom solutions for 50+ employee businesses.',
    faqs: [
      {
        question: 'What is included in Enterprise IT Solutions?',
        answer: 'Enterprise IT includes all Complete IT features plus a dedicated account team, 24/7/365 support with a 30-minute SLA, full compliance management (HIPAA, PCI, SOC2, CMMC), disaster recovery planning and testing, virtual CIO services, infrastructure project management, cloud migration services, advanced network design, annual penetration testing, and tabletop exercises.',
      },
      {
        question: 'How is pricing determined for Enterprise IT?',
        answer: 'Enterprise IT is quoted individually based on employee count, infrastructure complexity, and compliance requirements. It is designed for businesses with 50+ employees or complex IT environments.',
      },
      {
        question: 'What response time can we expect?',
        answer: '24/7/365 support with a 30-minute response SLA for critical issues.',
      },
      {
        question: 'How long does onboarding take?',
        answer: 'Onboarding typically takes 2-4 weeks, covering the full compliance documentation, disaster recovery plan and testing, and strategic IT roadmap deliverables.',
      },
      {
        question: 'Does this cover regulated industries like healthcare and finance?',
        answer: 'Yes, full compliance management for HIPAA, PCI, SOC2, and CMMC is included, along with board-level security reporting for leadership teams.',
      },
    ],
  },
]

export const cybersecurityServices: MSPService[] = [
  {
    id: 'security-essentials',
    name: 'Security Essentials',
    slug: 'security-essentials',
    category: 'cybersecurity',
    price: 29,
    priceLabel: '$29/user/mo',
    billingType: 'monthly',
    shortDescription: 'Core cybersecurity protection: antivirus, firewall management, email security',
    longDescription: `Essential cybersecurity protection for small businesses. Our Security Essentials package provides the core security tools every business needs: enterprise-grade antivirus, email security to block phishing and malware, and firewall management. We monitor your systems 24/7 for threats and provide monthly security reports so you always know your protection status. Perfect for businesses that need solid security without complexity.`,
    features: [
      'Enterprise antivirus/anti-malware',
      'Email security and spam filtering',
      'Phishing protection',
      'Firewall management',
      '24/7 threat monitoring',
      'Security patch management',
      'Web content filtering',
      'USB device control',
      'Monthly security reports',
      'Basic security awareness tips',
    ],
    benefits: [
      'Block ransomware and malware',
      'Prevent phishing attacks',
      'Protect sensitive business data',
      'Meet basic compliance requirements',
      'Peace of mind with 24/7 monitoring',
      'Simple, set-and-forget security',
    ],
    useCases: [
      'Small businesses needing basic protection',
      'Companies handling customer data',
      'Businesses with remote employees',
      'Professional services firms',
      'Retail and e-commerce businesses',
    ],
    deliverables: [
      'Security software deployment',
      'Firewall configuration',
      'Email security setup',
      'Monthly security reports',
      'Security best practices guide',
    ],
    timeline: 'Deployed in 1-2 days',
    seoKeywords: ['cybersecurity services Houston', 'small business security Conroe', 'email security Texas', 'antivirus management'],
    metaTitle: 'Houston Cybersecurity Essentials | $29/User/Mo',
    metaDescription: 'Essential cybersecurity for small businesses. Antivirus, email security, phishing protection. $29/user/month. Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'What is covered under Security Essentials?',
        answer: 'Security Essentials includes enterprise antivirus/anti-malware, email security and spam filtering, phishing protection, firewall management, 24/7 threat monitoring, security patch management, web content filtering, USB device control, and monthly security reports.',
      },
      {
        question: 'How fast can this be deployed?',
        answer: 'Security Essentials is typically deployed in 1-2 days, including security software deployment, firewall configuration, and email security setup.',
      },
      {
        question: 'Does this include employee security training?',
        answer: 'Security Essentials includes basic security awareness tips. A full security awareness training program is included in the Advanced Threat Protection package.',
      },
      {
        question: 'Who is Security Essentials designed for?',
        answer: 'It is built for small businesses needing basic protection, companies handling customer data, businesses with remote employees, professional services firms, and retail or e-commerce businesses.',
      },
    ],
  },
  {
    id: 'advanced-threat-protection',
    name: 'Advanced Threat Protection',
    slug: 'advanced-threat-protection',
    category: 'cybersecurity',
    price: 59,
    priceLabel: '$59/user/mo',
    billingType: 'monthly',
    shortDescription: 'Advanced security with EDR, SIEM, dark web monitoring, and incident response',
    longDescription: `Advanced cybersecurity for businesses facing sophisticated threats. Our Advanced Threat Protection package goes beyond basic security with Endpoint Detection and Response (EDR), Security Information and Event Management (SIEM), dark web monitoring for compromised credentials, and incident response support. We actively hunt for threats in your environment and respond immediately when threats are detected. Essential for businesses handling sensitive data or facing regulatory requirements.`,
    features: [
      'All Security Essentials features',
      'Endpoint Detection & Response (EDR)',
      'SIEM log monitoring and analysis',
      'Dark web credential monitoring',
      'Security incident response',
      'Advanced threat hunting',
      'Multi-factor authentication (MFA)',
      'Privileged access management',
      'Vulnerability scanning',
      'Quarterly security assessments',
      'Security awareness training',
      'Incident response plan',
    ],
    benefits: [
      'Detect advanced threats in real-time',
      'Rapid response to security incidents',
      'Know if credentials are compromised',
      'Meet compliance requirements',
      'Reduce breach risk significantly',
      'Expert security team on your side',
    ],
    useCases: [
      'Businesses handling sensitive data',
      'Healthcare organizations',
      'Financial services companies',
      'Legal and accounting firms',
      'Companies with compliance requirements',
    ],
    deliverables: [
      'All Security Essentials deliverables',
      'EDR deployment and configuration',
      'SIEM setup and monitoring',
      'Dark web monitoring alerts',
      'Incident response playbook',
      'Quarterly security reports',
      'Security awareness training program',
    ],
    timeline: 'Deployed in 3-5 days',
    seoKeywords: ['advanced threat protection Houston', 'EDR security Texas', 'cybersecurity monitoring Conroe', 'managed security services'],
    metaTitle: 'Conroe Advanced Threat Protection | EDR, SIEM | $59/User',
    metaDescription: 'Advanced cybersecurity with EDR, SIEM, dark web monitoring, and incident response. $59/user/month for Houston, Conroe, The Woodlands businesses.',
    faqs: [
      {
        question: 'What does Advanced Threat Protection add over Security Essentials?',
        answer: 'It includes all Security Essentials features plus Endpoint Detection & Response (EDR), SIEM log monitoring and analysis, dark web credential monitoring, security incident response, advanced threat hunting, multi-factor authentication, privileged access management, and vulnerability scanning.',
      },
      {
        question: 'How quickly is it deployed?',
        answer: 'Advanced Threat Protection is typically deployed in 3-5 days, including EDR deployment and configuration and SIEM setup and monitoring.',
      },
      {
        question: 'Does this include security awareness training?',
        answer: 'Yes, security awareness training and an incident response plan are included, along with quarterly security assessments.',
      },
      {
        question: 'Who needs this level of protection?',
        answer: 'It is aimed at businesses handling sensitive data, healthcare organizations, financial services companies, legal and accounting firms, and companies with compliance requirements.',
      },
    ],
  },
  {
    id: 'security-assessment',
    name: 'Security Assessment',
    slug: 'security-assessment',
    category: 'cybersecurity',
    price: 1500,
    priceLabel: '$1,500',
    billingType: 'one-time',
    shortDescription: 'Comprehensive security audit with vulnerability assessment and remediation plan',
    longDescription: `Understand your security posture with a comprehensive security assessment. Our Security Assessment service provides a thorough evaluation of your IT infrastructure, policies, and practices. We identify vulnerabilities, assess risks, and deliver a prioritized remediation plan. Perfect for businesses wanting to understand their security gaps, preparing for compliance audits, or evaluating their current security measures. Includes executive summary for leadership and technical details for IT teams.`,
    features: [
      'Network vulnerability scanning',
      'External penetration testing',
      'Password and access review',
      'Email security assessment',
      'Endpoint security evaluation',
      'Policy and procedure review',
      'Compliance gap analysis',
      'Risk scoring and prioritization',
      'Executive summary report',
      'Technical findings report',
      'Remediation roadmap',
      '60-minute review meeting',
    ],
    benefits: [
      'Understand your security weaknesses',
      'Prioritized action plan',
      'Support compliance requirements',
      'Reduce breach risk',
      'Justify security investments',
      'Expert third-party perspective',
    ],
    useCases: [
      'Businesses unsure of security status',
      'Companies preparing for audits',
      'Organizations after security incidents',
      'Businesses acquiring/merging',
      'Annual security checkups',
    ],
    deliverables: [
      'Executive summary (1-2 pages)',
      'Technical findings report (detailed)',
      'Vulnerability scan results',
      'Risk assessment matrix',
      'Prioritized remediation plan',
      'Compliance checklist (if applicable)',
    ],
    timeline: '1-2 weeks',
    seoKeywords: ['security assessment Houston', 'vulnerability assessment Texas', 'penetration testing Conroe', 'security audit'],
    metaTitle: 'Houston Security Assessment & Audit | $1,500 One-Time',
    metaDescription: 'Comprehensive security assessment with vulnerability scanning, penetration testing, and remediation plan. $1,500 one-time. Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'What do I get for the $1,500 Security Assessment?',
        answer: 'The assessment covers network vulnerability scanning, external penetration testing, password and access review, email security assessment, endpoint security evaluation, policy and procedure review, compliance gap analysis, and risk scoring and prioritization.',
      },
      {
        question: 'How long does the assessment take?',
        answer: 'The Security Assessment typically takes 1-2 weeks and concludes with a 60-minute review meeting.',
      },
      {
        question: 'Is this a one-time engagement or an ongoing service?',
        answer: 'It is a one-time, $1,500 engagement. Ongoing protection is available through Security Essentials or Advanced Threat Protection.',
      },
      {
        question: 'What deliverables do I receive at the end?',
        answer: 'An executive summary (1-2 pages), a detailed technical findings report, vulnerability scan results, a risk assessment matrix, a prioritized remediation plan, and a compliance checklist if applicable.',
      },
      {
        question: 'Who should get a Security Assessment?',
        answer: 'It is a good fit for businesses unsure of their current security status, companies preparing for audits, organizations recovering from a security incident, businesses going through an acquisition or merger, or those doing an annual security checkup.',
      },
    ],
  },
  {
    id: 'compliance-services',
    name: 'Compliance Services',
    slug: 'compliance-services',
    category: 'cybersecurity',
    price: 0,
    priceLabel: 'Custom Quote',
    billingType: 'custom',
    shortDescription: 'HIPAA, PCI-DSS, SOC2, CMMC compliance assistance and documentation',
    longDescription: `Navigate complex compliance requirements with expert guidance. Our Compliance Services help businesses achieve and maintain compliance with HIPAA, PCI-DSS, SOC2, CMMC, and other regulatory frameworks. We provide gap assessments, policy development, technical controls implementation, and ongoing compliance monitoring. Our team has experience with healthcare, financial services, government contractors, and other regulated industries. We help you pass audits and maintain compliance year-round.`,
    features: [
      'Compliance gap assessment',
      'Policy and procedure development',
      'Technical controls implementation',
      'Employee training programs',
      'Risk assessment documentation',
      'Vendor management assistance',
      'Audit preparation support',
      'Ongoing compliance monitoring',
      'Annual compliance reviews',
      'Incident response planning',
      'Business continuity planning',
      'Documentation management',
    ],
    benefits: [
      'Achieve compliance faster',
      'Reduce audit stress and costs',
      'Avoid fines and penalties',
      'Win contracts requiring compliance',
      'Protect customer trust',
      'Expert guidance throughout',
    ],
    useCases: [
      'Healthcare organizations (HIPAA)',
      'Payment processors (PCI-DSS)',
      'Government contractors (CMMC)',
      'SaaS companies (SOC2)',
      'Financial services (various)',
    ],
    deliverables: [
      'Gap assessment report',
      'Policy documentation package',
      'Technical controls checklist',
      'Training materials',
      'Audit-ready documentation',
      'Compliance roadmap',
    ],
    timeline: 'Varies by framework',
    seoKeywords: ['HIPAA compliance Houston', 'PCI compliance Texas', 'SOC2 preparation', 'CMMC compliance Conroe'],
    metaTitle: 'Houston HIPAA & PCI Compliance Services | Custom Quote',
    metaDescription: 'Expert compliance services for HIPAA, PCI-DSS, SOC2, and CMMC. Gap assessments, policy development, and audit preparation. Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'Which compliance frameworks do you help with?',
        answer: 'We provide compliance assistance for HIPAA, PCI-DSS, SOC2, CMMC, and other regulatory frameworks, including gap assessments, policy and procedure development, and technical controls implementation.',
      },
      {
        question: 'What is included in Compliance Services?',
        answer: 'A compliance gap assessment, policy and procedure development, technical controls implementation, employee training programs, risk assessment documentation, vendor management assistance, audit preparation support, and ongoing compliance monitoring with annual reviews.',
      },
      {
        question: 'How long does it take to become compliant?',
        answer: 'Timeline varies by framework and current gap; engagements are scoped individually after the initial gap assessment.',
      },
      {
        question: 'How is pricing structured?',
        answer: 'Compliance Services are custom-quoted based on the framework required and the complexity of your environment.',
      },
      {
        question: 'Who typically needs this service?',
        answer: 'Healthcare organizations (HIPAA), payment processors (PCI-DSS), government contractors (CMMC), SaaS companies (SOC2), and financial services firms with various compliance obligations.',
      },
    ],
  },
]

export const cloudServices: MSPService[] = [
  {
    id: 'microsoft-365-management',
    name: 'Microsoft 365 Management',
    slug: 'microsoft-365-management',
    category: 'cloud',
    price: 15,
    priceLabel: '$15/user/mo',
    billingType: 'monthly',
    shortDescription: 'Complete Microsoft 365 administration, support, and optimization',
    longDescription: `Maximize your Microsoft 365 investment with professional management. We handle everything from initial setup to ongoing administration, user management, security configuration, and support. Our M365 Management service ensures your tenant is secure, optimized, and your team is productive. Includes Teams administration, SharePoint management, Exchange Online configuration, and license optimization to reduce costs.`,
    features: [
      'Microsoft 365 tenant administration',
      'User provisioning and management',
      'Security and compliance configuration',
      'Teams and SharePoint administration',
      'Exchange Online management',
      'License optimization',
      'OneDrive for Business setup',
      'Conditional access policies',
      'Email signature management',
      'Shared mailbox management',
      'Distribution group management',
      'M365 support and troubleshooting',
    ],
    benefits: [
      'Optimized Microsoft 365 environment',
      'Reduced licensing costs',
      'Improved security posture',
      'Better team collaboration',
      'Expert support for M365 issues',
      'Stay current with new features',
    ],
    useCases: [
      'Businesses using Microsoft 365',
      'Companies migrating to M365',
      'Teams needing collaboration tools',
      'Organizations requiring email security',
      'Businesses needing SharePoint',
    ],
    deliverables: [
      'Tenant configuration audit',
      'Security baseline implementation',
      'User management procedures',
      'License optimization report',
      'M365 documentation',
    ],
    timeline: 'Setup in 1-3 days',
    seoKeywords: ['Microsoft 365 management Houston', 'M365 administration Texas', 'Office 365 support Conroe', 'Microsoft 365 consulting'],
    metaTitle: 'Houston Microsoft 365 Management | $15/User/Mo',
    metaDescription: 'Professional Microsoft 365 management including Teams, SharePoint, and Exchange administration. Security and optimization. $15/user/month. Houston area.',
    faqs: [
      {
        question: 'What does Microsoft 365 Management include?',
        answer: 'Tenant administration, user provisioning and management, security and compliance configuration, Teams and SharePoint administration, Exchange Online management, license optimization, OneDrive for Business setup, conditional access policies, and shared mailbox and distribution group management.',
      },
      {
        question: 'Can this reduce our Microsoft 365 licensing costs?',
        answer: 'Yes, license optimization is included and results in a license optimization report, one of the listed benefits is reduced licensing costs.',
      },
      {
        question: 'How fast can this be set up?',
        answer: 'Setup typically takes 1-3 days, including a tenant configuration audit and security baseline implementation.',
      },
      {
        question: 'Do you help businesses migrate to Microsoft 365?',
        answer: 'Yes, companies migrating to M365 are a listed use case for this service.',
      },
    ],
  },
  {
    id: 'cloud-backup',
    name: 'Cloud Backup Solutions',
    slug: 'cloud-backup',
    category: 'cloud',
    price: 10,
    priceLabel: '$10/user/mo',
    billingType: 'monthly',
    shortDescription: 'Automated cloud backup for endpoints, servers, and Microsoft 365',
    longDescription: `Protect your business data with automated, secure cloud backup. Our Cloud Backup Solutions provide comprehensive data protection for endpoints, servers, and Microsoft 365. Daily automated backups, encrypted storage, and rapid recovery ensure your business can survive any data loss scenario. From accidental deletion to ransomware, we keep your data safe and recoverable. Includes backup monitoring, testing, and restore assistance.`,
    features: [
      'Endpoint backup (workstations/laptops)',
      'Server backup',
      'Microsoft 365 backup',
      'Automated daily backups',
      'Encrypted cloud storage',
      'Point-in-time recovery',
      'Backup monitoring and alerts',
      'Monthly backup testing',
      'Rapid restore assistance',
      'Retention policies (30/60/90 days)',
      'Bandwidth throttling',
      'Bare-metal recovery option',
    ],
    benefits: [
      'Never lose critical business data',
      'Recover from ransomware attacks',
      'Meet compliance backup requirements',
      'Quick restoration when needed',
      'Peace of mind with monitoring',
      'Affordable data protection',
    ],
    useCases: [
      'Businesses with critical data',
      'Companies concerned about ransomware',
      'Compliance requirements (data retention)',
      'Businesses with mobile workers',
      'Organizations using Microsoft 365',
    ],
    deliverables: [
      'Backup software deployment',
      'Backup policy configuration',
      'Initial full backup',
      'Monitoring dashboard access',
      'Recovery documentation',
    ],
    timeline: 'Deployed in 1-2 days',
    seoKeywords: ['cloud backup Houston', 'data backup services Texas', 'Microsoft 365 backup Conroe', 'business backup solutions'],
    metaTitle: 'Houston Cloud Backup for Business | $10/User/Mo',
    metaDescription: 'Automated cloud backup for endpoints and Microsoft 365. Ransomware protection, fast recovery. $10/user/month. Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'What gets backed up?',
        answer: 'Endpoint backup for workstations and laptops, server backup, and Microsoft 365 backup, all with automated daily backups to encrypted cloud storage.',
      },
      {
        question: 'How long is my data retained?',
        answer: 'Retention policies of 30, 60, or 90 days are available, with point-in-time recovery and a bare-metal recovery option.',
      },
      {
        question: 'Does this protect against ransomware?',
        answer: 'Point-in-time recovery and rapid restore assistance help you recover from ransomware attacks or accidental deletion, one of the core benefits of the service.',
      },
      {
        question: 'How fast can backups be set up?',
        answer: 'Deployment typically takes 1-2 days, including backup software deployment, policy configuration, and an initial full backup.',
      },
      {
        question: 'Is backup testing included?',
        answer: 'Yes, monthly backup testing is included along with backup monitoring and alerts and rapid restore assistance when needed.',
      },
    ],
  },
  {
    id: 'cloud-migration',
    name: 'Cloud Migration',
    slug: 'cloud-migration',
    category: 'cloud',
    price: 2500,
    priceLabel: 'From $2,500',
    billingType: 'one-time',
    shortDescription: 'Migrate on-premise infrastructure to cloud (Azure, AWS, Google Cloud)',
    longDescription: `Move your business to the cloud with expert migration services. We plan and execute migrations from on-premise infrastructure to Azure, AWS, or Google Cloud. Our methodical approach minimizes downtime and ensures data integrity throughout the migration. Includes assessment, planning, migration execution, testing, and post-migration optimization. Perfect for businesses modernizing infrastructure or eliminating aging servers.`,
    features: [
      'Infrastructure assessment',
      'Cloud architecture design',
      'Migration planning and timeline',
      'Data migration',
      'Application migration',
      'Email migration (if needed)',
      'Identity migration (Active Directory)',
      'Testing and validation',
      'Cutover coordination',
      'Post-migration optimization',
      'Documentation and training',
      '90 days post-migration support',
    ],
    benefits: [
      'Eliminate aging server hardware',
      'Reduce infrastructure costs',
      'Improve reliability and uptime',
      'Enable remote work capabilities',
      'Scale resources as needed',
      'Disaster recovery built-in',
    ],
    useCases: [
      'Businesses with aging servers',
      'Companies enabling remote work',
      'Organizations needing scalability',
      'Businesses reducing IT overhead',
      'Companies consolidating locations',
    ],
    deliverables: [
      'Migration assessment report',
      'Cloud architecture documentation',
      'Migration runbook',
      'Completed migration',
      'Post-migration report',
      'Training documentation',
    ],
    timeline: '2-8 weeks depending on scope',
    seoKeywords: ['cloud migration Houston', 'Azure migration Texas', 'AWS migration Conroe', 'cloud consulting'],
    metaTitle: 'Houston Cloud Migration to Azure & AWS | From $2,500',
    metaDescription: 'Expert cloud migration services for Azure, AWS, and Google Cloud. Full assessment, planning, and execution from $2,500. Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'Which cloud platforms do you migrate to?',
        answer: 'We migrate on-premise infrastructure to Azure, AWS, or Google Cloud, including infrastructure assessment and cloud architecture design.',
      },
      {
        question: 'How long does a migration take?',
        answer: 'Migrations typically take 2-8 weeks depending on scope, covering data migration, application migration, and identity migration (Active Directory) where needed.',
      },
      {
        question: 'What is included in the starting price of $2,500?',
        answer: 'Infrastructure assessment, cloud architecture design, migration planning and timeline, migration execution, testing and validation, cutover coordination, and post-migration optimization.',
      },
      {
        question: 'Do you provide support after the migration is complete?',
        answer: 'Yes, 90 days of post-migration support is included along with documentation and training.',
      },
      {
        question: 'Who should consider a cloud migration?',
        answer: 'Businesses with aging server hardware, companies enabling remote work, organizations needing more scalability, and businesses consolidating multiple locations.',
      },
    ],
  },
]

export const supportServices: MSPService[] = [
  {
    id: 'break-fix-support',
    name: 'Break/Fix Support',
    slug: 'break-fix-support',
    category: 'support',
    price: 125,
    priceLabel: '$125/hour',
    billingType: 'one-time',
    shortDescription: 'On-demand IT support billed hourly for businesses not ready for managed services',
    longDescription: `Professional IT support when you need it, without monthly commitments. Our Break/Fix Support provides on-demand IT assistance billed hourly. Perfect for businesses with minimal IT needs, those testing our services before committing to managed IT, or for one-time projects. We handle troubleshooting, repairs, installations, and IT projects of all sizes. No contracts, no minimums, just expert help when you need it.`,
    features: [
      'Remote support',
      'On-site support (Houston/Conroe area)',
      'Hardware troubleshooting',
      'Software installation and support',
      'Network troubleshooting',
      'Virus and malware removal',
      'Data recovery assistance',
      'New computer setup',
      'Printer and peripheral support',
      'One-time projects',
    ],
    benefits: [
      'No monthly commitment',
      'Pay only for what you need',
      'Professional expertise on-demand',
      'Flexible scheduling',
      'Good for minimal IT needs',
      'Try before committing to managed',
    ],
    useCases: [
      'Small businesses with rare IT issues',
      'One-time IT projects',
      'Emergency IT support',
      'Businesses evaluating MSP services',
      'Supplement to internal IT',
    ],
    deliverables: [
      'Issue resolution',
      'Service documentation',
      'Recommendations for prevention',
    ],
    timeline: 'Same-day to next-day response',
    seoKeywords: ['IT support Houston', 'computer repair Conroe', 'on-demand IT Texas', 'hourly IT support'],
    metaTitle: 'Houston Break/Fix IT Support | $125/Hr, No Contract',
    metaDescription: 'On-demand IT support billed hourly with no contracts or minimums. Remote and on-site help at $125/hour. Serving Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'Do I need a monthly contract for Break/Fix Support?',
        answer: 'No. Break/Fix Support is billed hourly at $125/hour with no contracts and no monthly minimums, so you only pay for the help you need.',
      },
      {
        question: 'What kind of issues can you help with?',
        answer: 'Remote and on-site support (Houston/Conroe area), hardware troubleshooting, software installation and support, network troubleshooting, virus and malware removal, data recovery assistance, new computer setup, and printer/peripheral support.',
      },
      {
        question: 'How quickly can you respond?',
        answer: 'Break/Fix Support typically offers same-day to next-day response.',
      },
      {
        question: 'Is this a good fit if we already have some IT support in place?',
        answer: 'Yes. It works well as a supplement to internal IT or for businesses evaluating managed IT services before committing to a monthly plan.',
      },
    ],
  },
  {
    id: 'network-installation',
    name: 'Network Installation',
    slug: 'network-installation',
    category: 'support',
    price: 500,
    priceLabel: 'From $500',
    billingType: 'one-time',
    shortDescription: 'Business network design, installation, and configuration',
    longDescription: `Professional network installation for your business. We design and install business-grade networks including routers, switches, access points, and cabling. From small office setups to multi-floor installations, we ensure reliable, secure, and fast network connectivity. Includes network design, equipment recommendations, installation, configuration, and documentation. We also offer network upgrades and expansions for existing infrastructure.`,
    features: [
      'Network design and planning',
      'Equipment recommendations',
      'Router and firewall setup',
      'Switch installation',
      'Wireless access point deployment',
      'Network cabling (Cat6/Cat6a)',
      'VLAN configuration',
      'Guest network setup',
      'Network security configuration',
      'Speed and performance testing',
      'Network documentation',
      'Staff training',
    ],
    benefits: [
      'Reliable network connectivity',
      'Proper security configuration',
      'Scalable for growth',
      'Professional documentation',
      'Equipment warranty support',
      'Expert design and installation',
    ],
    useCases: [
      'New office setup',
      'Office relocation',
      'Network upgrades',
      'Adding wireless coverage',
      'Multi-floor installations',
    ],
    deliverables: [
      'Network design document',
      'Installed and configured equipment',
      'Network diagram',
      'Configuration documentation',
      'Speed test results',
    ],
    timeline: '1-5 days depending on scope',
    seoKeywords: ['network installation Houston', 'business networking Texas', 'office network setup Conroe', 'WiFi installation'],
    metaTitle: 'Houston Business Network Installation | From $500',
    metaDescription: 'Professional business network installation including design, equipment, cabling, and configuration. From $500. Serving Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'What is included in a network installation?',
        answer: 'Network design and planning, equipment recommendations, router and firewall setup, switch installation, wireless access point deployment, Cat6/Cat6a cabling, VLAN configuration, guest network setup, security configuration, and speed/performance testing.',
      },
      {
        question: 'How long does installation take?',
        answer: 'Typically 1-5 days depending on scope, from small office setups to larger installations.',
      },
      {
        question: 'Do you handle multi-floor or multi-location installs?',
        answer: 'Yes, multi-floor installations and network upgrades and expansions for existing infrastructure are covered use cases.',
      },
      {
        question: 'What do I receive once the installation is complete?',
        answer: 'A network design document, the installed and configured equipment, a network diagram, configuration documentation, and speed test results.',
      },
    ],
  },
  {
    id: 'it-consulting',
    name: 'IT Consulting',
    slug: 'it-consulting',
    category: 'support',
    price: 150,
    priceLabel: '$150/hour',
    billingType: 'one-time',
    shortDescription: 'Strategic IT consulting for technology planning and decision-making',
    longDescription: `Make informed technology decisions with expert IT consulting. Our IT Consulting services help businesses plan technology investments, evaluate solutions, and develop IT strategies aligned with business goals. Whether you're planning a major technology initiative, evaluating vendors, or developing an IT roadmap, we provide unbiased expert guidance. Perfect for businesses making significant technology decisions or needing strategic IT direction.`,
    features: [
      'Technology strategy development',
      'IT roadmap planning',
      'Vendor evaluation and selection',
      'Budget planning assistance',
      'Security strategy',
      'Cloud strategy',
      'Digital transformation guidance',
      'IT process improvement',
      'Technology due diligence (M&A)',
      'RFP development',
      'Project oversight',
      'Executive briefings',
    ],
    benefits: [
      'Unbiased expert advice',
      'Avoid costly technology mistakes',
      'Align IT with business goals',
      'Informed vendor decisions',
      'Clear technology roadmap',
      'Strategic IT direction',
    ],
    useCases: [
      'Planning major IT investments',
      'Evaluating technology vendors',
      'Developing IT strategy',
      'Digital transformation planning',
      'M&A technology assessment',
    ],
    deliverables: [
      'Consulting report/recommendations',
      'Technology roadmap (if applicable)',
      'Vendor comparison (if applicable)',
      'Executive presentation',
    ],
    timeline: 'Varies by engagement',
    seoKeywords: ['IT consulting Houston', 'technology consulting Texas', 'IT strategy Conroe', 'virtual CIO'],
    metaTitle: 'Houston IT Consulting & Tech Strategy | $150/Hr',
    metaDescription: 'Expert IT consulting for technology strategy, vendor selection, and IT roadmap planning. $150/hour for businesses in Houston, Conroe, The Woodlands.',
    faqs: [
      {
        question: 'What kind of IT consulting do you offer?',
        answer: 'Technology strategy development, IT roadmap planning, vendor evaluation and selection, budget planning assistance, security and cloud strategy, digital transformation guidance, and technology due diligence for M&A.',
      },
      {
        question: 'How is IT Consulting billed?',
        answer: 'Consulting is billed at $150/hour, with total timeline and cost varying by the scope of the engagement.',
      },
      {
        question: 'What do I receive at the end of an engagement?',
        answer: 'A consulting report with recommendations, a technology roadmap if applicable, a vendor comparison if applicable, and an executive presentation.',
      },
      {
        question: 'Who typically needs IT consulting?',
        answer: 'Businesses planning major IT investments, evaluating technology vendors, developing an IT strategy, going through digital transformation, or needing a technology assessment for a merger or acquisition.',
      },
    ],
  },
]

// Helper function to get all MSP services
export const allMSPServices: MSPService[] = [
  ...managedITServices,
  ...cybersecurityServices,
  ...cloudServices,
  ...supportServices,
]

// Get service by slug
export function getMSPServiceBySlug(slug: string): MSPService | undefined {
  return allMSPServices.find(service => service.slug === slug)
}
