export type ServiceCategory = 'core' | 'premium' | 'addon-basic' | 'addon-advanced'

export interface Service {
  id: string
  name: string
  slug: string
  category: ServiceCategory
  price: number
  priceLabel: string
  pricingUrl?: string
  shortDescription: string
  longDescription: string
  features: string[]
  benefits: string[]
  useCases: string[]
  deliverables: string[]
  timeline: string
  seoKeywords: string[]
  metaTitle: string
  metaDescription: string
}

export const corePackages: Service[] = [
  {
    id: 'plug-and-play',
    name: 'Plug and Play',
    slug: 'plug-and-play',
    category: 'core',
    price: 250,
    priceLabel: '$250',
    shortDescription: 'Professional design for WIX, GoDaddy, or similar platforms',
    longDescription: `Transform your existing website builder into a professional online presence. Perfect for businesses using platforms like WIX, GoDaddy, Squarespace, or Weebly who want a custom design without the complexity of a full rebuild. Our Plug and Play service delivers a professionally designed website that works seamlessly with your existing platform, combining the ease of use you love with the polished look your business deserves.`,
    features: [
      'Custom design on your existing platform',
      'Up to 5 pages (Home, About, Services, Contact, etc.)',
      'Mobile-responsive layout',
      'Basic SEO setup and optimization',
      'Contact form integration',
      'Social media links',
      'Google Analytics setup',
      'Image optimization',
      'One round of revisions',
    ],
    benefits: [
      'Keep using the platform you\'re familiar with',
      'Professional design without platform migration',
      'Quick turnaround time (1 week)',
      'Affordable entry point for small businesses',
      'No ongoing development costs',
      'Easy for you to update and maintain',
    ],
    useCases: [
      'Small businesses with existing WIX or GoDaddy sites',
      'Startups needing professional presence quickly',
      'Local service businesses (HVAC, plumbing, landscaping)',
      'Freelancers and consultants',
      'Businesses happy with their platform but not their design',
    ],
    deliverables: [
      'Professionally designed website',
      'Mobile-optimized layout',
      'SEO-ready structure',
      'Training on how to update content',
      '1 week of post-launch support',
    ],
    timeline: '1 week',
    seoKeywords: ['WIX website design', 'GoDaddy website redesign', 'affordable website design Houston', 'small business website Conroe'],
    metaTitle: 'Plug and Play Website Design | $250 | WIX, GoDaddy, Squarespace',
    metaDescription: 'Professional website design for WIX, GoDaddy, and other platforms. Custom design on your existing platform for just $250. 1-week turnaround. Houston & Conroe.',
  },
  {
    id: 'website-rebuild',
    name: 'Website Rebuild',
    slug: 'website-rebuild',
    category: 'core',
    price: 350,
    priceLabel: '$350',
    shortDescription: 'Complete website refresh or rebuild on existing platform',
    longDescription: `Breathe new life into your outdated website with a complete rebuild. Perfect for businesses whose websites look dated, perform poorly, or don't reflect their current brand. Our Website Rebuild service takes your existing content and transforms it into a modern, mobile-friendly, SEO-optimized website that converts visitors into customers. Whether you're on WordPress, WIX, or another platform, we'll give you a fresh start without starting from scratch.`,
    features: [
      'Complete website redesign',
      'Content migration and reorganization',
      'Modern, mobile-first layout',
      'Speed optimization',
      'SEO improvements',
      'Broken link fixes',
      'Image optimization',
      'Contact form updates',
      'Security updates (if applicable)',
      'Two rounds of revisions',
    ],
    benefits: [
      'Modernize your online presence',
      'Improve search engine rankings',
      'Better mobile experience for visitors',
      'Faster page load times',
      'Keep your existing domain and content',
      'Professional brand consistency',
    ],
    useCases: [
      'Businesses with outdated websites (5+ years old)',
      'Companies rebranding or pivoting',
      'Websites with poor mobile experience',
      'Sites with declining traffic or conversions',
      'Businesses expanding their services',
    ],
    deliverables: [
      'Fully redesigned website',
      'All content migrated and optimized',
      'Mobile-responsive design',
      'Speed and SEO improvements',
      'Training documentation',
      '2 weeks of post-launch support',
    ],
    timeline: '2 weeks',
    seoKeywords: ['website rebuild Houston', 'website redesign Conroe', 'modernize website Texas', 'website refresh services'],
    metaTitle: 'Website Rebuild Service | $350 | Modernize Your Outdated Site',
    metaDescription: 'Complete website rebuild and refresh service. Modernize your outdated site with mobile-responsive design and SEO improvements. $350 flat rate. Houston & Conroe.',
  },
  {
    id: 'standard-website',
    name: 'Standard Website',
    slug: 'standard-website',
    category: 'core',
    price: 850,
    priceLabel: '$850',
    shortDescription: 'Custom-built website with Home, About, Services, Contact pages',
    longDescription: `Get a fully custom-built website designed specifically for your business. Our Standard Website package is perfect for small to medium-sized businesses that need a professional online presence without the complexity of a full enterprise platform. Built with modern technologies like React and Next.js, your website will be fast, secure, SEO-optimized, and built to convert visitors into customers. Unlike template-based sites, every element is crafted to match your brand and serve your business goals.`,
    features: [
      'Custom design and development',
      'Up to 6 pages (Home, About, Services, Portfolio, Contact, etc.)',
      'Modern tech stack (React/Next.js)',
      'Fully responsive mobile design',
      'Contact forms with email notifications',
      'Google Analytics integration',
      'Advanced SEO optimization',
      'Fast page load times (optimized for Core Web Vitals)',
      'SSL certificate setup',
      'Free hosting setup assistance',
      'Three rounds of revisions',
    ],
    benefits: [
      'Custom-built, not template-based',
      'Better Google rankings (SEO optimized)',
      'Faster load times than WordPress',
      'Modern, professional design',
      'Scalable for future growth',
      'Full ownership of code',
      'Ongoing support available',
    ],
    useCases: [
      'Small businesses establishing online presence',
      'Service businesses (contractors, consultants, agencies)',
      'Professional services (lawyers, doctors, accountants)',
      'Local businesses targeting Houston/Conroe markets',
      'Companies migrating from outdated platforms',
    ],
    deliverables: [
      'Fully custom website (up to 6 pages)',
      'Mobile-responsive design',
      'SEO-optimized structure',
      'Contact form with email notifications',
      'Google Analytics dashboard',
      'Source code and documentation',
      '30 days of post-launch support',
    ],
    timeline: '3-4 weeks',
    seoKeywords: ['custom website development Houston', 'small business website Conroe', 'professional website design Texas', 'Next.js website development'],
    metaTitle: 'Custom Website Development | $850 | Houston & Conroe TX',
    metaDescription: 'Professional custom website development for small businesses. Fully responsive, SEO-optimized, built with modern tech. $850 flat rate. 3-4 week delivery. Houston & Conroe.',
  },
  {
    id: 'ecommerce-website',
    name: 'E-Commerce Website',
    slug: 'ecommerce-website',
    category: 'core',
    price: 1100,
    priceLabel: '$1,100',
    shortDescription: 'All Standard features + online store, payment gateway, and inventory sync',
    longDescription: `Launch your online store with a complete e-commerce solution built for growth. Our E-Commerce Website package includes everything from the Standard Website plus full online shopping functionality with Stripe payment processing, inventory management, and order tracking. Perfect for businesses ready to sell products or services online, this package gives you a professional online store without the monthly fees of platforms like Shopify or WooCommerce plugins.`,
    features: [
      'All Standard Website features',
      'Stripe payment gateway integration',
      'Product catalog (up to 50 products initially)',
      'Shopping cart functionality',
      'Secure checkout process',
      'Order management system',
      'Basic inventory tracking',
      'Vendor/supplier sync capabilities',
      'Customer accounts (optional)',
      'Email receipts and confirmations',
      'Sales tax calculation',
      'Shipping calculator',
      'Mobile-optimized checkout',
    ],
    benefits: [
      'No monthly platform fees (like Shopify)',
      'Accept credit cards securely',
      'Full control over your store',
      'Scalable as your business grows',
      'Integrated with your business systems',
      'Better SEO than marketplace platforms',
      'Lower transaction fees than Shopify',
    ],
    useCases: [
      'Retailers selling physical products',
      'Service businesses selling packages',
      'B2B companies with product catalogs',
      'Local businesses expanding online',
      'Wholesale suppliers with online ordering',
    ],
    deliverables: [
      'Complete e-commerce website',
      'Stripe payment integration',
      'Product management system',
      'Order tracking dashboard',
      'Customer email notifications',
      'Sales reporting',
      'Training on managing products and orders',
      '60 days of post-launch support',
    ],
    timeline: '4-6 weeks',
    seoKeywords: ['e-commerce website development Houston', 'online store development Texas', 'Stripe integration Conroe', 'custom shopping cart development'],
    metaTitle: 'E-Commerce Website Development | $1,100 | Online Store Solutions',
    metaDescription: 'Complete e-commerce website with Stripe payments, inventory management, and secure checkout. No monthly platform fees. $1,100 flat rate. Houston & Conroe.',
  },
]

export const premiumBuilds: Service[] = [
  {
    id: 'premium-build',
    name: '$2,500 Premium Build',
    slug: 'premium-build',
    category: 'premium',
    price: 2500,
    priceLabel: '$2,500',
    shortDescription: 'Advanced full-stack site (up to 15 pages) with admin portal and dashboard',
    longDescription: `Elevate your business with a premium full-stack web application. Our $2,500 Premium Build is designed for businesses that need more than a website—you need a complete business system. This package includes up to 15 pages, a custom admin portal, analytics dashboard, user management, and advanced features tailored to your specific workflow. Built with enterprise-grade technologies, your premium build will scale with your business and give you competitive advantages in your market.`,
    features: [
      'Up to 15 pages included',
      'Advanced full-stack development',
      'Custom admin portal',
      'Analytics dashboard with real-time data',
      'User role management',
      'Database design and optimization',
      'API development (if needed)',
      'Advanced authentication system',
      'Email automation',
      'File upload and management',
      'Advanced SEO and performance optimization',
      'Custom integrations (CRM, accounting, etc.)',
      'Unlimited revisions during development',
    ],
    benefits: [
      'Streamline business operations',
      'Data-driven decision making',
      'Competitive advantage in your market',
      'Scalable infrastructure',
      'Reduced manual work through automation',
      'Professional enterprise-level system',
    ],
    useCases: [
      'Growing businesses with complex workflows',
      'Companies managing multiple users/roles',
      'Businesses with custom data needs',
      'Service companies with client portals',
      'Organizations needing custom CRM',
    ],
    deliverables: [
      'Full-stack web application (up to 15 pages)',
      'Admin dashboard',
      'Analytics and reporting tools',
      'User management system',
      'Database architecture',
      'API documentation (if applicable)',
      'Training and documentation',
      '90 days of post-launch support',
    ],
    timeline: '6-8 weeks',
    seoKeywords: ['custom web application Houston', 'full-stack development Texas', 'admin portal development Conroe', 'business dashboard development'],
    metaTitle: 'Premium Web Application Development | $2,500 | Full-Stack Solutions',
    metaDescription: 'Custom full-stack web application with admin portal, analytics dashboard, and advanced features. Up to 15 pages. $2,500 flat rate. Houston & Conroe.',
  },
  {
    id: 'custom-business-platform',
    name: '$5,000 Custom Business Platform',
    slug: 'custom-business-platform',
    category: 'premium',
    price: 5000,
    priceLabel: '$5,000',
    shortDescription: 'Complete business system (up to 25 pages): CRM, client portals, APIs',
    longDescription: `Build a complete custom business platform tailored to your exact needs. The $5,000 Custom Business Platform package is perfect for businesses that need a unified system to manage everything in one place. This package includes up to 25 pages and we build you a custom platform that includes CRM, client portals, project management, invoicing, and all the integrations you need—owned entirely by you. Stop paying monthly SaaS fees and get full control of your business operations with a system built specifically for how you work.`,
    features: [
      'Up to 25 pages included',
      'Complete CRM system',
      'Client portal with login system',
      'Project/job management',
      'Invoicing and payments',
      'Email automation and templates',
      'Document management',
      'API integrations (accounting, email, etc.)',
      'Mobile-responsive design',
      'Multi-user access with roles',
      'Advanced reporting and analytics',
      'Automated workflows',
      'Notification system',
      'Custom features for your industry',
    ],
    benefits: [
      'Stop paying monthly SaaS fees',
      'All systems in one platform',
      'Full data ownership and control',
      'Customized to your exact workflow',
      'Scalable infrastructure',
      'Long-term cost savings',
      'Competitive advantage',
    ],
    useCases: [
      'Agencies managing client projects',
      'Service businesses with complex workflows',
      'Companies tired of expensive SaaS tools',
      'Businesses with custom processes',
      'Growing companies needing scalability',
    ],
    deliverables: [
      'Complete business management system (up to 25 pages)',
      'CRM and client portal',
      'Project management tools',
      'Invoicing and payment processing',
      'API integrations',
      'Mobile-responsive design',
      'Comprehensive training',
      '6 months of support and updates',
    ],
    timeline: '10-12 weeks',
    seoKeywords: ['custom CRM development Houston', 'business management system Texas', 'custom business platform Conroe', 'client portal development'],
    metaTitle: 'Custom Business Platform | $5,000 | Complete Business System',
    metaDescription: 'Build a complete custom business platform with CRM, client portals, project management, and integrations. Up to 25 pages. $5,000 flat rate. Houston & Conroe.',
  },
  {
    id: 'enterprise-platform',
    name: '$7,500 Enterprise Platform',
    slug: 'enterprise-platform',
    category: 'premium',
    price: 7500,
    priceLabel: '$7,500',
    shortDescription: 'Large-scale platform (up to 40 pages): admin system, staff roles, automation',
    longDescription: `Build an enterprise-grade platform that powers your entire organization. The $7,500 Enterprise Platform is designed for established businesses and organizations that need sophisticated systems with advanced automation, reporting, and multi-location support. This package includes up to 40 pages with everything from staff management and role-based access to automated workflows, advanced analytics, and integrations with your existing business tools.`,
    features: [
      'Up to 40 pages included',
      'Enterprise-grade architecture',
      'Advanced admin system',
      'Complex staff role management',
      'Multi-location/multi-tenant support',
      'Advanced workflow automation',
      'Comprehensive reporting suite',
      'Mobile-responsive design',
      'Advanced API integrations',
      'Real-time data synchronization',
      'Advanced security features',
      'Scalable cloud infrastructure',
      'White-label capabilities',
      'Advanced analytics and BI',
    ],
    benefits: [
      'Enterprise-level capabilities at fraction of cost',
      'Complete organizational automation',
      'Data-driven insights and reporting',
      'Multi-location management',
      'Competitive enterprise advantages',
      'Long-term scalability',
      'Full customization to your needs',
    ],
    useCases: [
      'Medium-sized organizations with complex needs',
      'Multi-location businesses',
      'Companies with advanced automation requirements',
      'Organizations replacing legacy systems',
      'Businesses needing robust reporting',
    ],
    deliverables: [
      'Complete enterprise platform (up to 40 pages)',
      'Admin and staff portals',
      'Automation engine',
      'Reporting and analytics suite',
      'API integrations',
      'Mobile-responsive design',
      'Documentation and training',
      '1 year of support and maintenance',
    ],
    timeline: '12-16 weeks',
    seoKeywords: ['enterprise web development Houston', 'custom enterprise platform Texas', 'business automation platform Conroe', 'enterprise software development'],
    metaTitle: 'Enterprise Platform Development | $7,500 | Large-Scale Solutions',
    metaDescription: 'Enterprise-grade platform with admin systems, automation, and advanced features. Up to 40 pages. $7,500 flat rate. Houston & Conroe.',
  },
  {
    id: 'enterprise-custom',
    name: 'Enterprise Custom',
    slug: 'enterprise-custom',
    category: 'premium',
    price: 0,
    priceLabel: 'Custom Quote',
    shortDescription: 'Large-scale enterprise solutions: mobile apps, 40+ pages, complex integrations',
    longDescription: `For organizations requiring large-scale enterprise solutions that exceed our standard packages, we offer custom enterprise development with personalized quotes. This includes projects requiring mobile applications (iOS/Android), 40+ pages, complex multi-system integrations, AI/ML features, or city/government-scale platforms. These projects typically start at $15,000+ and are scoped individually based on your exact requirements.`,
    features: [
      'Unlimited pages and features',
      'Native mobile applications (iOS/Android)',
      'Custom AI/ML integrations',
      'Complex multi-system integrations',
      'Government/municipality-grade security',
      'Multi-tenant SaaS architecture',
      'Advanced data warehousing',
      'Custom reporting and BI dashboards',
      'Legacy system migration',
      'Dedicated project management',
      'Extended support agreements',
      'SLA and uptime guarantees',
      'Compliance (HIPAA, SOC2, etc.)',
      'On-premise or hybrid deployment',
    ],
    benefits: [
      'Tailored solution for complex requirements',
      'Enterprise-grade security and compliance',
      'Dedicated development team',
      'Flexible engagement models',
      'Long-term partnership approach',
      'Full ownership of all code and IP',
      'Scalable to millions of users',
    ],
    useCases: [
      'City and municipal government websites',
      'Large corporations and enterprises',
      'Healthcare organizations requiring HIPAA compliance',
      'Financial institutions',
      'Multi-national organizations',
      'SaaS product development',
      'Projects requiring native mobile apps',
    ],
    deliverables: [
      'Comprehensive project scoping document',
      'Custom development timeline',
      'Dedicated project manager',
      'All custom features and integrations',
      'Complete documentation',
      'Training programs',
      'Custom support and maintenance agreements',
      'Source code and full IP ownership',
    ],
    timeline: 'Varies by project',
    seoKeywords: ['enterprise software development Houston', 'custom enterprise solutions Texas', 'government website development', 'large scale web development'],
    metaTitle: 'Enterprise Custom Development | Custom Quote | Large-Scale Solutions',
    metaDescription: 'Large-scale enterprise solutions for complex requirements. Mobile apps, 40+ pages, government-grade security. Custom quotes starting at $15,000+. Houston & Conroe.',
  },
]

// Add-ons will be in a separate file due to length
// addon-basic.ts and addon-advanced.ts
