import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Privacy Policy | StephensCode',
  description:
    'How StephensCode LLC collects, uses, discloses, and protects Personal Information across stephenscode.dev, our customer portal, and our checkout process, including your rights under the CCPA, TDPSA, and other privacy laws.',
  keywords: [
    'StephensCode privacy policy',
    'data privacy',
    'CCPA',
    'CPRA',
    'Texas Data Privacy and Security Act',
    'TDPSA',
    'GDPR',
    'cookie policy',
    'do not sell my personal information',
  ],
  openGraph: {
    title: 'Privacy Policy | StephensCode',
    description:
      'How StephensCode LLC collects, uses, discloses, and protects your Personal Information, and how to exercise your privacy rights.',
    url: 'https://www.stephenscode.dev/privacy',
    type: 'website',
  },
  alternates: {
    canonical: 'https://www.stephenscode.dev/privacy',
  },
}

const EFFECTIVE_DATE = 'July 24, 2026'

const toc = [
  { id: 'introduction', label: '1. Introduction & Scope' },
  { id: 'information-we-collect', label: '2. Information We Collect' },
  { id: 'how-we-use', label: '3. How We Use Your Information' },
  { id: 'legal-bases', label: '4. Legal Bases (Non-U.S. Visitors)' },
  { id: 'how-we-share', label: '5. How We Share Your Information' },
  { id: 'cookies', label: '6. Cookies, Analytics & Tracking' },
  { id: 'demo-sandboxes', label: '7. Interactive Demo Sandboxes' },
  { id: 'retention', label: '8. Data Retention' },
  { id: 'security', label: '9. Data Security' },
  { id: 'payments', label: '10. Payment Processing & PCI-DSS' },
  { id: 'customer-portal', label: '11. The Customer Portal' },
  { id: 'children', label: "12. Children's Privacy" },
  { id: 'california', label: '13. California Privacy Rights' },
  { id: 'texas', label: '14. Texas Privacy Rights' },
  { id: 'other-states', label: '15. Other U.S. State Rights' },
  { id: 'eea-uk', label: '16. EEA, UK & Swiss Rights' },
  { id: 'exercise-rights', label: '17. How to Exercise Your Rights' },
  { id: 'dnt-gpc', label: '18. Do Not Track & Global Privacy Control' },
  { id: 'transfers', label: '19. International Data Transfers' },
  { id: 'third-party-links', label: '20. Third-Party Links & Services' },
  { id: 'changes', label: '21. Changes to This Policy' },
  { id: 'governing-law', label: '22. Governing Law' },
  { id: 'contact', label: '23. Contact Us' },
]

const subprocessors = [
  {
    name: 'Stripe, Inc.',
    role: 'Payment processing, checkout, subscription billing, and refunds. Stripe receives your payment card details directly; we never receive, transmit, or store your full card number, CVC, or expiration date.',
    link: 'https://stripe.com/privacy',
  },
  {
    name: 'Google LLC (Firebase / Google Cloud Platform)',
    role: 'Authentication, database (Cloud Firestore), and file storage that power our customer portal (customer.stephenscode.dev) and order records.',
    link: 'https://policies.google.com/privacy',
  },
  {
    name: 'Google LLC (Google Analytics)',
    role: "Website usage analytics for stephenscode.dev (pages viewed, approximate location, device and browser information). Skipped automatically when your browser sends a Global Privacy Control signal — see Section 18.",
    link: 'https://policies.google.com/privacy',
  },
  {
    name: 'Ahrefs Pte. Ltd. (Ahrefs Web Analytics)',
    role: "Website usage analytics for stephenscode.dev. Ahrefs Web Analytics is cookieless and, per Ahrefs' own documentation, does not collect personal data or personally identifiable information by default.",
    link: 'https://ahrefs.com/web-analytics',
  },
  {
    name: 'Formspree, Inc.',
    role: 'Receives and routes submissions from our contact and quote-request forms to our team, acting as our service provider for that purpose. Formspree does not sell your Personal Information.',
    link: 'https://formspree.io/legal/privacy-policy/',
  },
  {
    name: 'Vercel Inc.',
    role: 'Hosting and content-delivery infrastructure for stephenscode.dev and customer.stephenscode.dev.',
    link: 'https://vercel.com/legal/privacy-policy',
  },
  {
    name: 'Email delivery provider (SMTP)',
    role: 'Delivers automated notification and confirmation emails generated by certain forms, such as demo appointment requests.',
    link: null,
  },
]

function Section({
  id,
  num,
  title,
  tone = 'white',
  children,
}: {
  id: string
  num: string
  title: string
  tone?: 'white' | 'muted'
  children: React.ReactNode
}) {
  return (
    <section id={id} className={`scroll-mt-24 py-12 ${tone === 'muted' ? 'bg-slate-50' : 'bg-white'}`}>
      <div className="max-w-4xl mx-auto px-4">
        <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-6">
          <span className="text-primary-600">{num}.</span> {title}
        </h2>
        <div className="space-y-4 text-slate-600 leading-relaxed">{children}</div>
      </div>
    </section>
  )
}

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="text-lg font-semibold text-slate-900 pt-2">{children}</h3>
}

export default function Privacy() {
  return (
    <main className="bg-white">
      {/* Hero */}
      <section className="bg-slate-900 text-white py-20">
        <div className="max-w-5xl mx-auto px-4">
          <p className="text-primary-400 font-semibold tracking-wide uppercase text-sm mb-3">
            Privacy Policy
          </p>
          <h1 className="text-4xl md:text-5xl font-bold mb-6">Your data, plainly explained</h1>
          <p className="text-lg text-slate-300 max-w-3xl">
            This Policy explains, in detail, what Personal Information StephensCode LLC
            collects across our website, customer portal, and checkout process; why we
            collect it; who we share it with; and the rights you have over it. We wrote it
            to be read, not just posted.
          </p>
          <p className="text-slate-400 text-sm mt-6">
            Effective date: {EFFECTIVE_DATE} &middot; Last updated: {EFFECTIVE_DATE}
          </p>
        </div>
      </section>

      {/* Table of contents */}
      <section className="py-10 bg-white border-b border-slate-200">
        <div className="max-w-5xl mx-auto px-4">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500 mb-4">
            Contents
          </h2>
          <nav aria-label="Table of contents">
            <ul className="grid gap-x-8 gap-y-2 sm:grid-cols-2 lg:grid-cols-3 text-sm">
              {toc.map((item) => (
                <li key={item.id}>
                  <a href={`#${item.id}`} className="text-primary-600 hover:text-primary-700 hover:underline">
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </div>
      </section>

      <Section id="introduction" num="1" title="Introduction & Scope">
        <p>
          StephensCode LLC (&ldquo;StephensCode,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;) is a veteran-owned, Texas-based web development, managed IT, and
          business automation company. This Privacy Policy explains how we collect, use,
          disclose, and protect Personal Information when you:
        </p>
        <ul className="list-disc list-inside space-y-1">
          <li>visit our website at stephenscode.dev;</li>
          <li>create or use an account in our customer portal at customer.stephenscode.dev;</li>
          <li>submit a contact form, quote request, or demo appointment request;</li>
          <li>purchase a website package, add-on, managed IT plan, or other service from us; or</li>
          <li>otherwise interact with us online</li>
        </ul>
        <p>(collectively, the &ldquo;Services&rdquo;).</p>
        <p>
          By using the Services, you agree to the collection and use of information in
          accordance with this Policy. If you do not agree with this Policy, please do not
          use the Services.
        </p>
        <p>
          This Policy does not apply to third-party websites, applications, or services that
          we do not own or control, even if linked from the Services, or to the fictional
          sample data displayed inside our interactive industry demo pages (see Section 7).
          &ldquo;Personal Information&rdquo; in this Policy means information that identifies,
          relates to, describes, or could reasonably be linked, directly or indirectly, with
          you or your household.
        </p>
      </Section>

      <Section id="information-we-collect" num="2" title="Information We Collect" tone="muted">
        <H3>2.1 Information you provide directly</H3>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong>Contact and quote requests.</strong> Name, email address, phone number,
            company name, service(s) of interest, budget range, project type, timeline, and
            any message or project details you choose to share, submitted through our
            contact form or Custom Solutions quote form.
          </li>
          <li>
            <strong>Demo appointment requests.</strong> If you request a consultation through
            one of our interactive industry demo pages, we collect your name, phone number,
            email address, the service you&apos;re interested in, your preferred date and
            time, and any notes you provide.
          </li>
          <li>
            <strong>Customer portal account information.</strong> If you register at
            customer.stephenscode.dev, we collect your full name, email address, password
            (stored in hashed form by our authentication provider &mdash; never in plain
            text), phone number, mailing address, and, optionally, a company name. If you
            sign in with Google, we receive your name and email address from your Google
            account instead.
          </li>
          <li>
            <strong>Support, update, and module requests.</strong> Descriptions of the work
            you&apos;re requesting when you submit an update request or module request
            through the customer portal, and any files you choose to upload with an update
            request.
          </li>
          <li>
            <strong>Feedback.</strong> If you rate our service below five stars inside the
            customer portal, we collect that rating and any written feedback, which is routed
            to our private feedback queue rather than a public review site. A five-star
            rating instead links you to leave a public review on Google, which is entirely
            optional and governed by Google&apos;s own terms.
          </li>
          <li>
            <strong>Payment and billing information.</strong> When you make a purchase, our
            payment processor, Stripe, collects your card details directly &mdash; see
            Section 10. We receive and store transaction-level details from Stripe, such as
            your email address, the amount, currency, plan or item purchased, transaction
            status, and Stripe&apos;s internal identifiers for that transaction.
          </li>
          <li>
            <strong>Password-gated proposal pages.</strong> Certain proposal pages we share
            with a specific prospective partner are protected by a single shared access
            password rather than an individual login. Entering that password does not
            identify you individually, and we do not collect your name or any other Personal
            Information through that gate.
          </li>
        </ul>

        <H3>2.2 Information collected automatically</H3>
        <p>
          When you visit stephenscode.dev, our analytics providers automatically collect
          certain information about your device and visit, including IP address (used to
          derive an approximate location), browser type and version, operating system,
          referring and exit pages, pages viewed, time spent on pages, and the date and time
          of your visit. See Section 6 for details on which providers we use and how you can
          opt out.
        </p>

        <H3>2.3 Information from third parties</H3>
        <ul className="list-disc list-inside space-y-2">
          <li>
            If you sign in to the customer portal with Google Sign-In, Google provides us
            your name and email address.
          </li>
          <li>
            If you register a customer portal account using an email address that matches a
            prior guest purchase, we automatically link that prior order history to your new
            account so you can view it in one place. You can ask us to unlink this at any
            time &mdash; see Section 11.
          </li>
          <li>Stripe provides us with confirmation and status information about payments you make.</li>
        </ul>
      </Section>

      <Section id="how-we-use" num="3" title="How We Use Your Information">
        <p>We use the Personal Information described above to:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>provide, operate, and maintain the Services, including your customer portal account and order history;</li>
          <li>process payments, subscriptions, invoices, and refunds;</li>
          <li>respond to your inquiries, quote requests, and support, update, and module requests;</li>
          <li>schedule and confirm demo appointments and consultations;</li>
          <li>send transactional communications, such as order confirmations, receipts, appointment confirmations, and account notices;</li>
          <li>maintain, secure, and improve the Services, including through website analytics;</li>
          <li>communicate with you about our services, consistent with your preferences and applicable law;</li>
          <li>detect, investigate, and prevent fraud, abuse, and security incidents;</li>
          <li>comply with our legal, tax, and accounting obligations; and</li>
          <li>enforce our agreements and protect our legal rights.</li>
        </ul>
        <p>
          We do not use your Personal Information for any purpose materially different from
          what is described in this Policy without notifying you.
        </p>
      </Section>

      <Section id="legal-bases" num="4" title="Legal Bases for Processing (Non-U.S. Visitors)" tone="muted">
        <p>
          If European data protection law (the GDPR, UK GDPR, or Swiss FADP) applies to our
          processing of your Personal Information, we rely on the following legal bases:
        </p>
        <ul className="list-disc list-inside space-y-1">
          <li><strong>Performance of a contract</strong> &mdash; for example, providing a website package or IT service you purchased;</li>
          <li><strong>Legitimate interests</strong> &mdash; for example, securing and improving the Services or responding to your inquiries, provided those interests are not overridden by your rights and interests;</li>
          <li><strong>Consent</strong> &mdash; for example, certain analytics or marketing communications, which you may withdraw at any time; and</li>
          <li><strong>Legal obligation</strong> &mdash; for example, retaining financial records as required by tax law.</li>
        </ul>
      </Section>

      <Section id="how-we-share" num="5" title="How We Share Your Information">
        <p>
          <strong>We do not sell your Personal Information for money</strong>, and we do not
          disclose it to third parties for their own direct marketing purposes. We share
          Personal Information only as follows:
        </p>

        <H3>Service providers</H3>
        <p>
          We use the third-party service providers below to operate the Services. Each
          processes Personal Information only on our behalf and for the purposes described
          here.
        </p>
        <div className="overflow-x-auto -mx-4 px-4">
          <div className="grid gap-4 sm:grid-cols-2 min-w-[560px] sm:min-w-0">
            {subprocessors.map((sp) => (
              <div key={sp.name} className="border border-slate-200 rounded-xl p-5 bg-white">
                <h4 className="font-semibold text-slate-900 mb-1">{sp.name}</h4>
                <p className="text-sm text-slate-600 leading-relaxed">{sp.role}</p>
                {sp.link && (
                  <a
                    href={sp.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs text-primary-600 hover:text-primary-700 hover:underline mt-2 inline-block"
                  >
                    Their privacy policy &rarr;
                  </a>
                )}
              </div>
            ))}
          </div>
        </div>

        <H3>Legal requirements and safety</H3>
        <p>
          We may disclose Personal Information if required to do so by law, subpoena, or
          other legal process, or where we believe in good faith that disclosure is
          necessary to protect the rights, property, or safety of StephensCode, our users, or
          the public.
        </p>

        <H3>Business transfers</H3>
        <p>
          If StephensCode is involved in a merger, acquisition, financing, reorganization, or
          sale of some or all of its assets, Personal Information may be transferred as part
          of that transaction. We will notify you of any such change in ownership or use of
          your Personal Information through this Policy or a notice on our website.
        </p>

        <H3>With your consent</H3>
        <p>
          We may share Personal Information for any other purpose disclosed to you at the
          time of collection, or with your consent.
        </p>
      </Section>

      <Section id="cookies" num="6" title="Cookies, Analytics & Tracking Technologies">
        <p>
          stephenscode.dev uses the following analytics tools, each loaded on every page
          unless noted otherwise:
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong>Google Analytics (GA4).</strong> Sets cookies (such as <code>_ga</code>{' '}
            and <code>_ga_*</code>) that can persist for up to two years, and reports page
            views, approximate location, and device/browser information back to Google. GA4
            is not loaded for visitors whose browser sends a Global Privacy Control signal
            &mdash; see Section 18.
          </li>
          <li>
            <strong>Ahrefs Web Analytics.</strong> Per Ahrefs&apos; own documentation, this
            tool is cookieless and does not collect personal data or personally identifiable
            information by default.
          </li>
        </ul>
        <p>
          We do not currently use advertising or remarketing pixels of our own. Our content
          security policy allow-lists a small number of additional Google analytics-related
          domains as a defensive/technical measure; we do not knowingly use them for
          advertising, but because Google Analytics&apos; own configuration (such as{' '}
          <em>Google Signals</em>) can, in some configurations, be interpreted as
          &ldquo;sharing&rdquo; Personal Information for cross-context behavioral advertising
          under the CCPA/CPRA, we treat that as a possibility and honor opt-out signals as
          described in Section 18 out of caution.
        </p>
        <H3>Local and session storage</H3>
        <p>
          We also use limited browser storage that never leaves your device and is not
          Personal Information: a session-storage flag that remembers you&apos;ve entered the
          password on a password-gated proposal page, and local-storage data that powers the
          fictional shopping-cart and order simulations on our interactive demo pages (see
          Section 7), which is cleared automatically.
        </p>
        <H3>Managing cookies</H3>
        <p>
          Most browsers let you block or delete cookies through their settings. You can also
          install the{' '}
          <a
            href="https://tools.google.com/dlpage/gaoptout"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary-600 hover:underline"
          >
            Google Analytics Opt-out Browser Add-on
          </a>{' '}
          to prevent your data from being used by Google Analytics on any website. Blocking
          cookies may affect the functionality of some features of the Services.
        </p>
      </Section>

      <Section id="demo-sandboxes" num="7" title="Interactive Demo Sandboxes" tone="muted">
        <p>
          Our /demos pages showcase example websites for various industries (such as a
          barbershop, handyman service, photography studio, cleaning company, or tutoring
          business). Some of these demos include interactive features, such as a shopping
          cart or order simulation, styled to look like a real business.
        </p>
        <p>
          Any &ldquo;cart,&rdquo; &ldquo;order,&rdquo; or similar data you enter into these
          demo sandboxes is fictional. It is stored only in your own browser&apos;s local
          storage, is never transmitted to StephensCode or to any real business, and is
          cleared automatically. If a demo page includes an actual appointment-request form,
          that form is clearly presented as a request to consult with StephensCode and is
          handled as real Personal Information under Section 2.1 &mdash; not as sandbox data.
        </p>
      </Section>

      <Section id="retention" num="8" title="Data Retention">
        <p>
          We retain Personal Information for as long as necessary to provide the Services and
          fulfill the purposes described in this Policy, unless a longer period is required
          or permitted by law:
        </p>
        <ul className="list-disc list-inside space-y-1">
          <li>Customer portal account data: for as long as your account remains active, and for a reasonable period afterward in case you wish to reactivate it or as needed for our legal and accounting obligations.</li>
          <li>Transaction and billing records: for as long as required by applicable tax, accounting, and financial recordkeeping laws (typically at least seven years).</li>
          <li>Contact form and quote request submissions that do not lead to an engagement: generally up to 24 months.</li>
          <li>Website analytics data: according to the retention settings configured within Google Analytics; we do not independently extend that retention period.</li>
        </ul>
        <p>
          You may request earlier deletion of your Personal Information as described in
          Section 17, subject to our legal and legitimate business retention needs.
        </p>
      </Section>

      <Section id="security" num="9" title="Data Security">
        <p>
          We implement administrative, technical, and physical safeguards designed to protect
          Personal Information from unauthorized access, use, disclosure, alteration, or
          destruction, including encrypted transmission (TLS) for data sent to and from the
          Services, and reliance on payment and infrastructure providers &mdash; including
          Stripe, Google Cloud/Firebase, and Vercel &mdash; that maintain their own security
          programs. Access controls governing who and what can read or write Personal
          Information within our own systems are an active, ongoing part of this program, and
          we continue to strengthen them as our infrastructure evolves.
        </p>
        <p>
          <strong>
            No method of transmission over the internet or method of electronic storage is
            completely secure, and we cannot guarantee absolute security.
          </strong>{' '}
          You are responsible for keeping your customer portal password confidential and for
          using a strong, unique password. If you believe your account has been compromised,
          contact us immediately using the information in Section 23.
        </p>
        <p>
          For more detail on our broader security program and the standards it is aligned
          to, see our{' '}
          <Link href="/security" className="text-primary-600 hover:underline">
            Security &amp; Trust page
          </Link>
          .
        </p>
      </Section>

      <Section id="payments" num="10" title="Payment Processing & PCI-DSS Compliance" tone="muted">
        <p>
          All payment card processing for the Services is handled directly by Stripe, Inc., a
          PCI-DSS Level 1 certified payment processor. When you make a payment, your card
          details are entered directly into a Stripe-hosted checkout interface and
          transmitted directly to Stripe.{' '}
          <strong>
            StephensCode&apos;s servers never receive, process, transmit, or store your full
            card number, CVC/security code, or expiration date.
          </strong>
        </p>
        <p>
          We store limited transaction metadata that Stripe returns to us &mdash; such as the
          amount charged, currency, the plan or item purchased, transaction status, your
          email address, and Stripe&apos;s internal identifiers for the transaction &mdash;
          in order to maintain your order history, provide customer support, and comply with
          our accounting obligations. Stripe&apos;s own privacy policy governs Stripe&apos;s
          handling of your payment information; see{' '}
          <a
            href="https://stripe.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary-600 hover:underline"
          >
            stripe.com/privacy
          </a>
          .
        </p>
      </Section>

      <Section id="customer-portal" num="11" title="The Customer Portal">
        <p>
          If you create an account at customer.stephenscode.dev, the following practices
          apply in addition to the rest of this Policy:
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong>Order linking.</strong> When you register using an email address that
            matches a previous guest purchase, we automatically associate that order history
            with your new account so it is visible in one place. If you would prefer your
            prior order history not be linked, contact us using the information in Section
            23 and we will unlink it.
          </li>
          <li>
            <strong>Update and module requests.</strong> Descriptions and files you submit
            through the portal are shared internally with our team to scope and fulfill your
            request, and may be retained as part of your project history.
          </li>
          <li>
            <strong>Feedback.</strong> Feedback submitted for ratings below five stars is
            treated as private feedback to our team, as described in Section 2.1.
          </li>
          <li>
            <strong>Plan upgrades.</strong> Selecting an upgrade or add-on inside the portal
            initiates a checkout session directly with Stripe as described in Section 10; the
            portal itself does not process your card details.
          </li>
          <li>
            <strong>Authorized personnel.</strong> Our authorized personnel may access
            customer portal data as needed to provide support, process billing, and maintain
            the Services.
          </li>
        </ul>
      </Section>

      <Section id="children" num="12" title="Children's Privacy" tone="muted">
        <p>
          The Services are intended for businesses and individuals who are at least 18 years
          old and are not directed to children. We do not knowingly collect Personal
          Information from children under 13 (or under 16 where a higher threshold applies
          under applicable law). If you believe a child has provided us with Personal
          Information, please contact us and we will promptly delete it.
        </p>
      </Section>

      <Section id="california" num="13" title="California Privacy Rights (CCPA/CPRA)">
        <p>
          StephensCode LLC may not independently meet every threshold that triggers mandatory
          compliance with the California Consumer Privacy Act, as amended by the California
          Privacy Rights Act (together, the &ldquo;CCPA&rdquo;). Regardless, we voluntarily
          extend the following rights to California residents as a matter of policy.
        </p>
        <H3>Categories of Personal Information we collect</H3>
        <p>In the preceding 12 months, we have collected the following CCPA categories of Personal Information, as described in Section 2: identifiers (such as name, email, phone number); commercial information (such as your order and transaction history); internet or other electronic network activity information (such as pages viewed and referring URLs); geolocation data (approximate, derived from your IP address); professional or employment-related information (such as a company name you provide to us); and account login credentials.</p>
        <p>
          Account login credentials are the only category of{' '}
          <em>Sensitive Personal Information</em>, as defined by the CPRA, that we collect. We
          use it solely to authenticate you and secure your account &mdash; a permitted
          business purpose that does not trigger a right to limit its use under the CPRA.
        </p>
        <H3>Your rights</H3>
        <ul className="list-disc list-inside space-y-1">
          <li><strong>Right to know</strong> what Personal Information we have collected, used, disclosed, and shared about you;</li>
          <li><strong>Right to delete</strong> Personal Information we have collected from you, subject to certain exceptions;</li>
          <li><strong>Right to correct</strong> inaccurate Personal Information;</li>
          <li><strong>Right to opt out</strong> of the sale or sharing of Personal Information &mdash; see Section 18;</li>
          <li><strong>Right to limit</strong> use and disclosure of Sensitive Personal Information (not applicable here beyond what is described above); and</li>
          <li><strong>Right to non-discrimination</strong> for exercising any of these rights.</li>
        </ul>
        <p>
          You may designate an authorized agent to submit a request on your behalf, subject
          to verification. We do not disclose your Personal Information to third parties for
          their own direct marketing purposes.
        </p>
      </Section>

      <Section id="texas" num="14" title="Texas Privacy Rights (TDPSA)" tone="muted">
        <p>
          As a Texas-based company, we also want Texas residents to have clear rights under
          the Texas Data Privacy and Security Act (&ldquo;TDPSA&rdquo;), regardless of whether
          StephensCode LLC independently meets every threshold that would make the TDPSA
          mandatory for us. If you are a Texas resident, you have the right to:
        </p>
        <ul className="list-disc list-inside space-y-1">
          <li>confirm whether we are processing your Personal Information and access it;</li>
          <li>correct inaccuracies in your Personal Information;</li>
          <li>delete your Personal Information;</li>
          <li>obtain a copy of your Personal Information in a portable format; and</li>
          <li>opt out of the processing of your Personal Information for targeted advertising, the sale of Personal Information, or profiling in furtherance of decisions that produce legal or similarly significant effects.</li>
        </ul>
        <p>
          If we decline to act on your request, you may appeal by replying to our decision
          email. If your appeal is denied, you may contact the{' '}
          <a
            href="https://www.texasattorneygeneral.gov/consumer-protection/file-consumer-complaint"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary-600 hover:underline"
          >
            Texas Attorney General&apos;s office
          </a>
          .
        </p>
      </Section>

      <Section id="other-states" num="15" title="Other U.S. State Privacy Rights">
        <p>
          If you are a resident of Virginia, Colorado, Connecticut, Utah, Oregon, Montana,
          Delaware, Iowa, Nebraska, New Hampshire, New Jersey, or another state with a
          comprehensive consumer privacy law, you may have rights similar to those described
          in Sections 13 and 14, including rights to access, correct, delete, and port your
          Personal Information, and to opt out of targeted advertising, sale, or certain
          profiling. We will honor validated requests to the extent required by applicable
          law. Contact us using the information in Section 23 to exercise these rights,
          regardless of which state you live in.
        </p>
      </Section>

      <Section id="eea-uk" num="16" title="EEA, UK & Swiss Privacy Rights" tone="muted">
        <p>
          If European data protection law (the GDPR, UK GDPR, or Swiss FADP) applies to our
          processing of your Personal Information, you have the right to: access your
          Personal Information; rectify inaccurate Personal Information; erase your Personal
          Information; restrict or object to processing (including for direct marketing);
          receive a portable copy of your Personal Information; and withdraw consent at any
          time without affecting the lawfulness of processing before its withdrawal. You also
          have the right to lodge a complaint with your local data protection supervisory
          authority.
        </p>
      </Section>

      <Section id="exercise-rights" num="17" title="How to Exercise Your Rights">
        <p>
          To exercise any of the rights described in this Policy, email us at{' '}
          <a href="mailto:info@stephenscode.dev" className="text-primary-600 hover:underline">
            info@stephenscode.dev
          </a>{' '}
          with &ldquo;Privacy Request&rdquo; in the subject line, or write to the mailing
          address in Section 23. Please include enough information for us to verify your
          identity &mdash; typically the email address associated with your inquiry, order,
          or account &mdash; and to understand your request.
        </p>
        <p>
          We will respond within the time frame required by applicable law (for example, 45
          days under the CCPA and TDPSA, extendable once by an additional 45 days with notice
          to you). There is no fee to submit a request, though we may decline unreasonably
          repetitive or manifestly excessive requests as permitted by law.
        </p>
      </Section>

      <Section id="dnt-gpc" num="18" title="Do Not Track & Global Privacy Control" tone="muted">
        <p>
          Some browsers send a &ldquo;Do Not Track&rdquo; signal. There is no common industry
          standard for how businesses should respond to it, and stephenscode.dev does not
          currently respond to Do Not Track signals specifically.
        </p>
        <p>
          We do honor the{' '}
          <a
            href="https://globalprivacycontrol.org"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary-600 hover:underline"
          >
            Global Privacy Control
          </a>{' '}
          (GPC) signal: when your browser or a browser extension sends a GPC signal, our
          server detects it and does not load Google Analytics for that visit. This applies
          automatically, with no account or login required. Ahrefs Web Analytics continues to
          run regardless of GPC, because &mdash; per its own privacy design &mdash; it does
          not use cookies or collect personal data in the first place (see Section 6).
        </p>
      </Section>

      <Section id="transfers" num="19" title="International Data Transfers">
        <p>
          StephensCode is based in the United States, and our service providers &mdash;
          including Stripe, Google Cloud/Firebase, and Vercel &mdash; process and store data
          primarily in the United States, though they may maintain infrastructure in other
          countries. If you access the Services from outside the United States, your
          information may be transferred to, stored, and processed in the United States and
          other countries that may not have data protection laws equivalent to those in your
          jurisdiction. Where required, we rely on our service providers&apos; own transfer
          safeguards (such as Standard Contractual Clauses) for these transfers.
        </p>
      </Section>

      <Section id="third-party-links" num="20" title="Third-Party Links & External Services" tone="muted">
        <p>
          The Services contain links to third-party websites and services we do not control,
          including outbound links on our interactive demo pages, a link to leave a Google
          review, and a link to our SACVPN product page. This Policy does not apply to those
          third-party sites; please review their own privacy policies.
        </p>
      </Section>

      <Section id="changes" num="21" title="Changes to This Policy">
        <p>
          We may update this Policy from time to time to reflect changes in our practices or
          for other operational, legal, or regulatory reasons. We will update the
          &ldquo;Last updated&rdquo; date at the top of this page when we do, and, for
          material changes, we will provide additional notice (such as an email to customer
          portal account holders or a notice on our website) before the change takes effect.
        </p>
      </Section>

      <Section id="governing-law" num="22" title="Governing Law" tone="muted">
        <p>
          This Policy, and any dispute arising from it or from the Services, is governed by
          the laws of the State of Texas, without regard to its conflict-of-laws principles,
          except where applicable law requires otherwise.
        </p>
      </Section>

      {/* Contact CTA */}
      <section id="contact" className="scroll-mt-24 py-16 bg-slate-900 text-white">
        <div className="max-w-5xl mx-auto px-4">
          <h2 className="text-3xl font-bold mb-4">
            <span className="text-primary-400">23.</span> Contact Us
          </h2>
          <p className="text-slate-300 max-w-3xl mb-6">
            Questions about this Policy, or requests to exercise any of the rights described
            above, can go to our team directly. We&apos;re a small company &mdash; a real
            person reads and answers this inbox.
          </p>
          <div className="flex flex-wrap gap-4 mb-8">
            <a
              href="mailto:info@stephenscode.dev"
              className="inline-block bg-primary-600 hover:bg-primary-700 text-white font-semibold px-6 py-3 rounded-lg transition-colors"
            >
              info@stephenscode.dev
            </a>
            <Link
              href="/contact"
              className="inline-block border border-slate-500 hover:border-white text-white font-semibold px-6 py-3 rounded-lg transition-colors"
            >
              Contact us
            </Link>
          </div>
          <div className="text-slate-400 text-sm space-y-1">
            <p>StephensCode LLC</p>
            <p>2378 Strong Horse Dr, Conroe, TX 77301</p>
            <p>(936) 323-4527</p>
          </div>
        </div>
      </section>
    </main>
  )
}
